"""Render plain SQL from the explicit model. Run with --check in build gates."""
import argparse
import itertools
from pathlib import Path
from model import ENTITIES, AUDIT, TEMPORAL, MODULES

ROOT = Path(__file__).resolve().parent
EXAMPLE = ROOT.parents[1] / "examples/customer360-postgres"
EPOCH = "2025-01-01 00:00:00+00"


def literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return str(value).upper()
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def columns(e):
    return e.columns + (TEMPORAL if e.history else []) + AUDIT


def insert(e, values, start=EPOCH, end="infinity", deleted=False):
    values = dict(values)
    if e.history:
        values.update(valid_from_dts=start, valid_to_dts=end, is_current=end == "infinity",
                      is_deleted=deleted, deleted_dts=start if deleted else None)
    values.update(created_dts=EPOCH, updated_dts=EPOCH)
    names = ", ".join(values)
    return f"INSERT INTO {e.qualified} ({names}) VALUES ({', '.join(literal(v) for v in values.values())});\n"


BY_NAME = {e.qualified: e for e in ENTITIES}

# Authored derived-object contracts. No consumer needs to parse their SQL.
DERIVED = {
    "semantic.column_catalogue": ("Live structural facts joined to authored meaning with provenance.", ["semantic.column_metadata"]),
    "semantic.data_product_manifest": ("Generated product orientation and trusted entrypoints.", ["semantic.data_product_registry", "semantic.data_product_orientation"]),
    "semantic.relationship_edges": ("Bidirectional registered relationship edges.", ["semantic.table_relationship"]),
    "semantic.relationship_paths": ("Cycle-free logical relationship paths of at most four hops.", ["semantic.table_relationship"]),
    "semantic.access_edges": ("Relationship endpoints resolved to approved consumable objects.", ["semantic.table_relationship", "semantic.access_object"]),
    "semantic.access_relationship_paths": ("Bounded paths whose joins name consumable objects verbatim.", ["semantic.table_relationship", "semantic.access_object"]),
    "semantic.lineage_graph": ("Distinct active source-to-job and job-to-target lineage edges.", ["observability.data_lineage"]),
    "semantic.lineage_run_latest": ("Latest execution evidence for each active lineage definition.", ["observability.data_lineage", "observability.lineage_run"]),
    "observability.validation_run_latest": ("Latest run for each product and producer.", ["observability.validation_run"]),
    "observability.trust_map": ("Authoritative area confidence, with expiry and absent evidence disclosed.", ["observability.validation_area", "observability.validation_run", "semantic.data_product_registry"]),
    "observability.trust_map_evidence": ("Latest native area evidence before cautious producer reconciliation.", ["observability.validation_area", "observability.validation_run", "semantic.data_product_registry"]),
    "search.searchable": ("Current vectors joined to authoritative Product content.", ["search.entity_embedding", "domain.product"]),
    "prediction.enriched": ("Current model outputs joined to authoritative Customer context.", ["prediction.model_prediction", "domain.customer"]),
}


def row(table, **values):
    return insert(BY_NAME[table], values)


def ddl(e):
    fields = [f"    {n} {t}" for n, t, _ in columns(e)]
    if e.name.endswith('_keymap'):
        fields[0] = f"    {e.key} BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)"
        fields.append(f"    UNIQUE ({e.key}, {e.natural})")
    if e.qualified == 'observability.change_event':
        fields[0] = f"    {e.key} BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)"
    if e.schema == 'domain' and e.history:
        fields.append(f"    FOREIGN KEY ({e.key}, {e.natural}) REFERENCES {e.qualified}_keymap ({e.key}, {e.natural})")
    if e.schema == 'search':
        fields.append("    CHECK (array_ndims(embedding)=1 AND array_lower(embedding,1)=1 AND cardinality(embedding)=embedding_dimensions AND array_position(embedding,NULL) IS NULL)")
    fields.append(f"    PRIMARY KEY ({e.key}" + (", valid_from_dts)" if e.history else ")"))
    fields.extend("    " + x for x in e.constraints)
    vocabularies = {
        "scope_level": ("USER","TEAM","ORGANIZATION","AGENT"),
        "module_name": tuple(MODULES), "source_module": tuple(MODULES),
        "deployment_status": ("DEPLOYED","PLANNED","DEPRECATED"),
        "decision_status": ("PROPOSED","ACCEPTED","SUPERSEDED","DEPRECATED"),
        "decision_category": ("ARCHITECTURE","SCHEMA","NAMING","PERFORMANCE","SECURITY","INTEGRATION","OPERATIONAL"),
        "term_category": ("ENTITY","ATTRIBUTE","METRIC","BUSINESS_RULE","CLASSIFICATION","REFERENCE_CODE"),
        "complexity": ("SIMPLE","MODERATE","COMPLEX","ADVANCED"),
        "session_status": ("ACTIVE","COMPLETED","ABANDONED"),
        "interaction_type": ("QUERY","ACTION","DECISION","EXPLANATION"),
        "outcome_status": ("SUCCESS","PARTIAL","FAILED"),
        "run_status": ("SUCCESS","FAILED","PARTIAL","RUNNING"),
        "scope_kind": ("PRODUCT","MODULE","ENTITY","PATTERN","CAPABILITY"),
        "area_status": ("pass","fail","partial","not-validated","no-evidence"),
        "confidence": ("strong","partial","weak","unknown"),
        "severity": ("INFO","WARNING","ERROR","CRITICAL"),
        "dataset_role": ("PRIMARY","JOINED"),
        "object_kind": ("ENTITY","COLUMN","METRIC"),
    }
    if e.name == "validation_check":
        vocabularies["status"] = ("PASSED","FAILED","ERROR")
    for name, _, _ in e.columns:
        if name in vocabularies:
            fields.append(f"    CHECK ({name} IN ({','.join(literal(x) for x in vocabularies[name])}))")
    if e.history:
        fields += ["    CHECK(valid_from_dts < valid_to_dts)",
                   "    CHECK(is_current = (valid_to_dts = 'infinity'::TIMESTAMPTZ))",
                   "    CHECK(is_deleted = (deleted_dts IS NOT NULL))"]
    sql = f"CREATE TABLE {e.qualified} (\n" + ",\n".join(fields) + "\n);\n"
    sql += f"COMMENT ON TABLE {e.qualified} IS {literal(e.description)};\n"
    for name, _, meaning in columns(e):
        sql += f"COMMENT ON COLUMN {e.qualified}.{name} IS {literal(meaning)};\n"
    # Runtime tables deliberately have no public view. Host API binds scope itself.
    if not e.runtime:
        exposed = e.columns + ([TEMPORAL[0]] if e.history else [])
        sql += f"CREATE VIEW {e.schema}.v_{e.name} AS SELECT " + ", ".join(c[0] for c in exposed)
        sql += f" FROM {e.qualified}"
        if e.history:
            sql += " WHERE is_current AND valid_to_dts='infinity'::TIMESTAMPTZ AND NOT is_deleted"
        sql += ";\n"
        sql += f"COMMENT ON VIEW {e.schema}.v_{e.name} IS {literal('Consumer contract: ' + e.description)};\n"
    if e.history:
        sql += f"CREATE FUNCTION {e.schema}.at_{e.name}(at_dts TIMESTAMPTZ) RETURNS SETOF {e.qualified} LANGUAGE SQL STABLE AS $$ SELECT * FROM {e.qualified} WHERE valid_from_dts <= at_dts AND at_dts < valid_to_dts AND NOT is_deleted; $$;\n"
        sql += f"CREATE UNIQUE INDEX ON {e.qualified} ({e.key}) WHERE is_current;\n"
        sql += f"ALTER TABLE {e.qualified} ADD EXCLUDE USING gist ({e.key} WITH =, tstzrange(valid_from_dts, valid_to_dts, '[)') WITH &&);\n"
    return sql + "\n"


def relationships():
    edges = []
    for e in ENTITIES:
        if e.schema == "domain" and e.history:
            edges.append((e.qualified, e.key, e.qualified + "_keymap", e.key))
    edges += [
        ("domain.account", "customer_id", "domain.customer", "customer_id"),
        ("domain.account", "product_id", "domain.product", "product_id"),
        ("domain.transaction", "account_id", "domain.account", "account_id"),
        ("search.entity_embedding", "entity_id", "domain.product", "product_id"),
        ("search.entity_embedding", "embedding_model", "semantic.model_metadata", "model_key"),
        ("prediction.feature_value", "entity_id", "domain.customer", "customer_id"),
        ("prediction.feature_value", "feature_name", "semantic.feature_definition", "feature_name"),
        ("prediction.model_prediction", "entity_id", "domain.customer", "customer_id"),
        ("prediction.model_prediction", "model_key", "semantic.model_metadata", "model_key"),
        ("observability.lineage_run", "lineage_id", "observability.data_lineage", "lineage_id"),
        ("memory.agent_interaction", "session_id", "memory.agent_session", "session_id"),
        ("semantic.metric_expression", "metric_name", "semantic.metric", "metric_name"),
        ("semantic.metric_dataset", "metric_name", "semantic.metric", "metric_name"),
        ("semantic.metric_dataset", "entity_name", "semantic.entity_metadata", "entity_name"),
        ("semantic.column_metadata", "table_name", "semantic.entity_metadata", "table_name"),
        ("semantic.primary_object", "module_name", "semantic.data_product_map", "module_name"),
        ("semantic.data_product_orientation", "product_id", "semantic.data_product_registry", "product_id"),
        ("observability.validation_area", "run_id", "observability.validation_run", "run_id"),
        ("observability.validation_check", "run_id", "observability.validation_run", "run_id"),
    ]
    # Metadata column registration has a compound (schema,table) join, recorded
    # separately below in the compiler; do not publish an ambiguous table-name join.
    edges = [e for e in edges if e[0] != "semantic.column_metadata"]
    for name in ("design_decision", "business_glossary", "query_cookbook", "implementation_note", "change_log"):
        edges.append(("memory." + name, "source_module", "memory.module_registry", "module_name"))
    edges.append(("memory.change_log", "related_decision_id", "memory.design_decision", "decision_id"))
    return edges


def registration():
    sql = row("semantic.data_product_registry", product_id="customer360", product_version="1.0", product_status="ACTIVE",
              owner_team="Synthetic demo maintainers", trust_authoritative_producer="postgres-reference", approved_entrypoint="domain.v_customer",
              approved_access_mode="VIEW", max_evidence_age_days=7)
    for module, purpose in MODULES.items():
        sql += row("semantic.data_product_map", module_name=module, container_name=module, module_purpose=purpose,
                   deployment_status="DEPLOYED", module_version="1.0")
    linked = {x for a, _, b, _ in relationships() for x in (a, b)}
    for e in ENTITIES:
        sql += row("semantic.entity_metadata", entity_name=e.qualified, entity_description=e.description, module_name=e.schema,
                   container_name=e.schema, table_name=e.name, view_name=None if e.runtime else "v_" + e.name,
                   surrogate_key_column=e.key, natural_key_column=e.natural or e.key, temporal_pattern=e.profile,
                   current_flag_column="is_current" if e.history else None, deleted_flag_column="is_deleted" if e.history else None,
                   standalone_reason=None if e.qualified in linked else "Independent registry or evidence collection; see DD-SEMANTIC-003.")
        for name, _, meaning in columns(e):
            sql += row("semantic.column_metadata", column_metadata_id=e.qualified + "." + name,
                       container_name=e.schema, table_name=e.name, column_name=name, business_description=meaning,
                       is_pii=name in ("display_name", "user_key"), is_sensitive=e.runtime,
                       data_classification="PUBLIC", source="Authored deployment model")
        sql += row("semantic.access_object", object_identity=e.qualified, access_role="BASE", represents_entity=e.qualified,
                   object_grain="one physical record or historical version", is_agent_consumable=False,
                   resolves_to_object=None, access_note="Governed full contract; private to the database administration boundary.")
        if not e.runtime:
            sql += row("semantic.access_object", object_identity=e.schema + ".v_" + e.name, access_role="PASSTHROUGH",
                       represents_entity=e.qualified, object_grain="one current non-deleted record" if e.history else "one record",
                       is_agent_consumable=True, resolves_to_object=e.qualified, access_note="Consumer view protected by PostgreSQL grants.")
            sql += row("semantic.primary_object", object_identity=e.schema + ".v_" + e.name, module_name=e.schema,
                       object_type="VIEW", object_role="ANALYTICAL_QUERY" if e.schema in ("domain", "prediction", "search") else "REFERENCE_LOOKUP",
                       usage_guidance=e.description)
    for i, (a, ac, b, bc) in enumerate(relationships()):
        sql += row("semantic.table_relationship", relationship_id=f"REL-{i:03}", source_entity=a, source_column=ac,
                   target_entity=b, target_column=bc, cardinality="MANY_TO_ONE", relationship_type="FOREIGN_KEY", is_mandatory=True)
    resources = [
        ("MANIFEST", "semantic.data_product_manifest"), ("TRUST_MAP", "observability.trust_map"),
        ("MODULE_MAP", "semantic.v_data_product_map"), ("OBJECT_CATALOGUE", "semantic.v_access_object"),
        ("ENTITY_CATALOGUE", "semantic.v_entity_metadata"), ("COLUMN_CATALOGUE", "semantic.column_catalogue"),
        ("RELATIONSHIP_CATALOGUE", "semantic.v_table_relationship"), ("RELATIONSHIP_PATHS", "semantic.access_relationship_paths"),
        ("LINEAGE", "semantic.lineage_graph"), ("QUERY_COOKBOOK", "memory.v_query_cookbook"),
        ("GLOSSARY", "memory.v_business_glossary"), ("DESIGN_DECISIONS", "memory.v_design_decision"),
        ("POLICY", "semantic.v_role_policy"), ("QUALITY", "observability.v_data_quality_metric")]
    for order, (role, obj) in enumerate(resources, 1):
        sql += row("semantic.data_product_orientation", resource_role=role, product_id="customer360", object_identity=obj,
                   discovery_order=order, is_required=True)
    for token, meaning, target in [("v_", "Consumer view; read access_object to resolve role", "VIEW"),
                                    ("at_", "Half-open point-in-time SQL function", "FUNCTION"),
                                    ("_id", "Stable surrogate reference", "COLUMN"), ("_dts", "Zone-aware instant", "COLUMN")]:
        sql += row("semantic.naming_standard", standard_value=token, meaning=meaning, applies_to=target)
    for tier, who in [("READ", "Analysts and reporting users."), ("AGENT", "Automated agents and tools."), ("ADMIN", "Product owners and stewards.")]:
        sql += row("semantic.role_policy", role_name=f"customer360_role_{tier.lower()}", description=who,
                   enforcement="Native grants; runtime rows restricted to authenticated session_user. Owners and superusers remain privileged.")
    sql += row("semantic.metric", metric_name="Total posted amount", metric_description="Signed posted AUD amount, once per transaction; excludes deleted records.",
               unit="AUD", aggregation_type="SUM", grain_description="current transaction", is_additive=True)
    sql += row("semantic.metric_expression", expression_id="amount-postgres", metric_name="Total posted amount", sql_dialect="postgres", expression_text="sum(amount)")
    sql += row("semantic.metric_dataset", metric_dataset_id="amount-transactions", metric_name="Total posted amount", entity_name="domain.transaction", dataset_role="PRIMARY")
    sql += row("semantic.semantic_synonym", synonym_id="client", object_kind="ENTITY", object_name="domain.customer", synonym_text="client")
    sql += row("semantic.model_metadata", model_key="toy-lexical-v1", model_version="1", model_purpose="Offline demonstration only; lexical banking categories, not learned semantic embeddings.", dimensions=3,
               computation_logic="Three axes: savings, payments, credit word presence; each axis has a 0.1 floor. search.embed uses identical query and content logic.")
    sql += row("semantic.model_metadata", model_key="toy-score-v1", model_version="1", model_purpose="Uncalibrated example of model provenance.", dimensions=None, computation_logic="1 - spend_intensity; no predictive performance claim.")
    sql += row("semantic.feature_definition", feature_name="spend_intensity", feature_version="1", computation_logic="least(1, greatest(0, sum(amount)/1000)) using transactions posted strictly before observation_dts; source state as-of observation_dts.",
               source_entity="domain.transaction", refresh_frequency="monthly demonstration snapshots", unit="fraction [0,1]")
    for obj, members in {
        "search.searchable": [("search.entity_embedding", "ANCHOR", ""), ("domain.product", "INNER", "entity_id = product_id")],
        "prediction.enriched": [("prediction.model_prediction", "ANCHOR", ""), ("domain.customer", "INNER", "entity_id = customer_id")],
    }.items():
        sql += row("semantic.access_object", object_identity=obj, access_role="COMPOSITE", represents_entity=None,
                   object_grain="one current enhancement record", is_agent_consumable=True, resolves_to_object=None,
                   access_note="Context is joined from current Domain; no content is persisted here.")
        for member, role, predicate in members:
            sql += row("semantic.access_composition", access_composition_id=obj+":"+member, composite_object=obj,
                       member_entity=member, member_role=role, join_path=predicate, is_grain_contributor=False)
    # Curate view fields from the explicit deployment model, not from DDL parsing.
    # PostgreSQL view-column comments are not relied upon; curated meanings stay queryable.
    for e in ENTITIES:
        if e.runtime:
            continue
        for name, _, meaning in e.columns + ([TEMPORAL[0]] if e.history else []):
            sql += row("semantic.column_metadata", column_metadata_id=f"{e.schema}.v_{e.name}.{name}",
                       container_name=e.schema, table_name="v_"+e.name, column_name=name, business_description=meaning,
                       is_pii=name in ("display_name", "user_key"), is_sensitive=False, data_classification="PUBLIC", source="Explicit view projection in model")
    special_fields = {
        "data_type": "Deployed PostgreSQL physical type, read from the catalogue.",
        "is_nullable": "Physical field accepts SQL null.",
        "declared_type_source": "Provenance of the resolved physical type.",
        "description_source": "Authored or missing meaning provenance.",
        "documentation_covered": "Whether a curated meaning exists for this field.",
        "trust_map": "Verbatim trust resource resolved from orientation.",
        "module_map": "Verbatim module resource resolved from orientation.",
        "object_catalogue": "Verbatim access resource resolved from orientation.",
        "resources": "Ordered generated resource manifest; not a second authored registry.",
        "visited": "Ordered entity identities on a cycle-free relationship path.",
        "hops": "Number of joins on the path, at most four.",
        "source_object": "Access-resolved source object identity.",
        "target_object": "Access-resolved target object identity.",
        "source_node": "Source table or job identity in the active lineage graph.",
        "target_node": "Target job or table identity in the active lineage graph.",
        "edge_type": "Lineage relationship kind; produces in the table-grain binding.",
        "coverage": "Executed checks divided by defined checks; null for zero definitions.",
    }
    meanings = {n: d for e in ENTITIES for n, _, d in columns(e)}
    meanings.update(special_fields)
    for obj, (meaning, members) in DERIVED.items():
        schema, view = obj.split(".")
        sql += f"COMMENT ON VIEW {obj} IS {literal(meaning)};\n"
        if obj not in ("search.searchable", "prediction.enriched"):
            sql += row("semantic.access_object", object_identity=obj, access_role="COMPOSITE", represents_entity=None,
                       object_grain=meaning, is_agent_consumable=True, resolves_to_object=None, access_note="Derived from registered metadata or evidence; no security isolation.")
            for i, member in enumerate(members):
                sql += row("semantic.access_composition", access_composition_id=obj+":"+member, composite_object=obj,
                           member_entity=member, member_role="ANCHOR" if i==0 else "LEFT", join_path="See authored discovery.sql for transformation; consume this derived object as one unit.",
                           is_grain_contributor=i>0)
        sql += row("semantic.primary_object", object_identity=obj, module_name=schema, object_type="VIEW",
                   object_role="AGENT_ENTRYPOINT" if schema=="semantic" else "ANALYTICAL_QUERY", usage_guidance=meaning)
        # Engine catalogue supplies output field identities at deployment; authored
        # model supplies every meaning. Unknown fields fail metadata coverage.
        cases = " ".join(f"WHEN {literal(n)} THEN {literal(d)}" for n,d in meanings.items())
        sql += f"""INSERT INTO semantic.column_metadata
SELECT schema_name||'.'||table_name||'.'||column_name,schema_name,table_name,column_name,
 CASE column_name {cases} ELSE NULL END,
 column_name IN ('display_name','user_key'),false,'PUBLIC','Authored derived-field contract',
 '{EPOCH}'::TIMESTAMPTZ,'{EPOCH}'::TIMESTAMPTZ
FROM (SELECT current_database() AS database_name, n.nspname AS schema_name, c.relname AS table_name,
 a.attname AS column_name, pg_catalog.format_type(a.atttypid,a.atttypmod) AS data_type,
 NOT a.attnotnull AS is_nullable, pg_catalog.col_description(c.oid,a.attnum) AS comment
 FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class c ON c.oid=a.attrelid
 JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace
 WHERE a.attnum>0 AND NOT a.attisdropped AND c.relkind IN ('r','v','p')
 AND n.nspname IN ('domain','semantic','search','prediction','observability','memory')) physical WHERE database_name=current_database() AND schema_name={literal(schema)} AND table_name={literal(view)};
"""
    return sql


DECISIONS = {
    "domain": [
        ("Temporal strategy", "DEC-TEMPORAL-PATTERN=scd2 rather than bi-temporal: synthetic sources have effective changes but no as-known correction requirement. Transaction-time reconstruction is not offered."),
        ("Stable allocation", "DEC-SURROGATE-ALLOCATION=keymap: all four reference targets retain permanent natural-key allocation; no recycled identifiers."),
        ("Lifecycle and audit", "DEC-DELETE-STRATEGY=soft-delete; deletion inserts a tombstone. DEC-COLUMN-STRATEGY uses canonical audit inline and table-level change evidence in Observability.")],
    "semantic": [
        ("Comments and registration", "Comments hold field meaning; explicit deployment registration holds relationships, profiles and access roles. Live catalogue facts carry separate provenance."),
        ("Trust authority", "postgres-reference is the designated producer even when it is the only producer. Trust is advisory and expires after seven days."),
        ("Standalone registries", "Independent naming, policy, feature/model, retention and runtime learning registries require no instance traversal. Column metadata uses its explicit schema/table pair; the hybrid catalogue joins both.")],
    "search": [
        ("Vector dimensions", "DOUBLE PRECISION[] binds toy-lexical-v1. Real products deploy one table per dimension/model family and register each; do not mix incompatible vectors."),
        ("Baseline and optional pgvector", "Exact SQL cosine similarity is the baseline. Optional pgvector HNSW/IVFFlat needs a separate extension, model contract and recall evaluation."),
        ("Embedding provenance", "Toy lexical embedding is deterministic and computed in SQL for both query and source text. It demonstrates the interface, not general semantic quality. Superseded vectors use SCD2 and soft deletion.")],
    "prediction": [
        ("Feature history", "DEC-TEMPORAL-PATTERN=scd2 departs from bi-temporal: observation is availability time and feature validity cannot precede it. Retrospective feature corrections are prohibited; a production correction requirement needs bitemporal storage."),
        ("Engineered values", "Only clipped aggregate spend intensity is persisted. Descriptive context is obtained by identifier join-back. Definitions and model logic belong to Semantic."),
        ("Model and deletion", "Toy score is reproducible from the exact feature observation timestamp. It is not calibrated. Soft deletion preserves prior feature and model evidence.")],
    "observability": [
        ("Evidence separation", "DEC-QUALITY-STORAGE=observability: data quality time series, validation coverage, flow definitions and executions are separate entities."),
        ("Retention", "DEC-AUDIT-RETENTION uses an explicit synthetic-demo policy: definitions for product life; events 90 days; validation 365 days. Operator executes archival, never a hidden build job."),
        ("Optional graph facets", "Graph-native and column-lineage facets are omitted. Table-level active lineage remains discoverable in Semantic. No external Graph Explorer dependency.")],
    "memory": [
        ("Versioned documentation", "DEC-TEMPORAL-PATTERN=scd2: documentation corrections supersede prior decisions; soft deletion retains withdrawn guidance."),
        ("Runtime privacy", "Runtime USER rows are restricted to session_user by native RLS. TEAM, ORGANIZATION and AGENT sharing is denied until an authenticated membership policy is deployed."),
        ("Self-contained capture", "Every module captures decisions, glossary, cookbook and release notes with provenance. Runtime stores process context and counts, never business result rows.")],
}


def documentation():
    sql = ""
    def doc(table, **values):
        values.update(authored_by="reference-implementation", source_artifact="examples/customer360-postgres", authored_dts=EPOCH)
        return row("memory." + table, **values)
    for module, purpose in MODULES.items():
        sql += doc("module_registry", module_name=module, container_name=module, deployment_status="DEPLOYED", module_version="1.0", module_purpose=purpose)
        for i, (title, reason) in enumerate(DECISIONS[module], 1):
            sql += doc("design_decision", decision_id=f"DD-{module.upper()}-{i:03}", decision_version=1, decision_title=title,
                       context=purpose, alternatives="Server platform; embedded file; external serving application, according to capability.", rationale=reason,
                       consequences="DEC-TIMESTAMP-ZONE=zone-aware UTC. Capability gaps remain visible in the trust map.",
                       decision_status="ACCEPTED", decision_category="ARCHITECTURE", source_module=module)
        sql += doc("change_log", change_id=f"CL-{module.upper()}-001", version_number="1.0", change_title="Initial portable synthetic module release",
                   change_type="INITIAL_RELEASE", source_module=module, related_decision_id=f"DD-{module.upper()}-001")
        sql += doc("query_cookbook", recipe_id=f"QC-{module.upper()}-001", recipe_title="Inspect " + module,
                   use_case=purpose, target_module=module.upper(), query_template="SELECT * FROM " + next(e.schema + ".v_" + e.name for e in ENTITIES if e.schema == module),
                   complexity="SIMPLE", is_batch=False, source_module=module)
    terms = {
        "domain": [("Customer", "Party owning an account."), ("Account", "Agreement linking a customer to an offering."), ("Posted amount", "Signed money movement in AUD.")],
        "semantic": [("Consumable object", "Registered surface an agent resolves before reading."), ("Join path", "Registered chain of relationships, not guessed from names."), ("Metric", "Business measure with a declared grain and calculation.")],
        "search": [("Embedding", "Numeric representation generated by a named model."), ("Cosine similarity", "Vector directional agreement; larger values rank first."), ("Join-back", "Obtaining authoritative content by identifier from Domain.")],
        "prediction": [("Spend intensity", "Clipped total posted amount divided by 1000 AUD."), ("Observation instant", "Earliest availability of a computed feature snapshot."), ("Toy score", "One minus spend intensity; not a calibrated probability.")],
        "observability": [("Trust map", "Area-level coverage and strength of executed checks."), ("Quality measurement", "A measured data property, separate from validation coverage."), ("Lineage flow", "A transformation definition, independent of executions.")],
        "memory": [("Design memory", "Versioned why, how and change rationale."), ("Privacy scope", "Runtime USER ownership enforced against authenticated session_user by RLS."), ("Process context", "Task metadata excluding business query results.")],
    }
    for module, entries in terms.items():
        for term, meaning in entries:
            sql += doc("business_glossary", term=term, term_category="BUSINESS_RULE", definition=meaning, source_module=module)
    for ident, module, title, reason in [
        ("DD-ACCESS-001", "memory", "Three database roles", "Independent READ, AGENT and ADMIN NOLOGIN roles. READ and AGENT query approved views. AGENT writes its USER runtime rows and appends outcomes. ADMIN maintains the product. Login membership is assigned by the operator."),
        ("DD-DISCOVERY-001", "semantic", "Name-only bootstrap", "Given customer360, read semantic.data_product_registry then ordered orientation and generated manifest. Trust precedes analytical use; approved domain.v_customer is the initial business entrypoint. Product-less discovery lists the registry."),
        ("DD-DOMAIN-004", "domain", "Placement and portability", "One database per product and environment, with six co-located schemas. Native heap storage is the baseline; external storage requires a separately governed lifecycle."),
        ("DD-SEMANTIC-004", "semantic", "Reusable SQL delivery", "A small explicit Python model generates plain SQL with shared temporal fields and complete registration. The checked build.sql runs in CLI/JDBC without Python. No Jinja dependency or DDL parsing during discovery.")]:
        sql += doc("design_decision", decision_id=ident, decision_version=1, decision_title=title, context="PostgreSQL server product",
                   alternatives="See rationale for considered choices.", rationale=reason, consequences="Login provisioning and secure server operation remain deployment obligations.",
                   decision_status="ACCEPTED", decision_category="SECURITY" if ident == "DD-ACCESS-001" else "ARCHITECTURE", source_module=module)
    sql += doc("query_cookbook", recipe_id="QC-SEMANTIC-002", recipe_title="Discover the ERD", use_case="Render registered relationships",
               target_module="SEMANTIC", query_template="SELECT source_entity, source_column, target_entity, target_column FROM semantic.v_table_relationship ORDER BY relationship_id",
               complexity="SIMPLE", is_batch=False, source_module="semantic")
    for a, b in itertools.combinations(MODULES, 2):
        # A meaningful, metadata-driven pair recipe: objects plus their published
        # confidence. Works for every deployed pair without fictitious instance joins.
        query = ("SELECT e.entity_name, e.view_name, t.confidence FROM semantic.v_entity_metadata e "
                 "LEFT JOIN observability.trust_map t ON t.scope_kind='MODULE' AND t.scope_id=e.module_name "
                 f"WHERE e.module_name IN ('{a}','{b}') ORDER BY e.entity_name")
        sql += doc("query_cookbook", recipe_id=f"QC-CROSS-{a.upper()}-{b.upper()}", recipe_title=f"Plan use of {a} and {b}",
                   use_case="Resolve surfaces and disclose area confidence for the pair before use.", target_module="CROSS",
                   query_template=query, complexity="MODERATE", is_batch=False, source_module=a)
    sql += doc("implementation_note", note_id="IN-MEMORY-001", note_title="Runtime isolation boundary", note_content="RLS authenticates scope_identifier against session_user, never a caller-set session variable. Privileged owners and superusers can bypass policy; do not grant these roles to agents.", note_category="SECURITY", source_module="memory")
    return sql


def render_all():
    files = {}
    for module in MODULES:
        files[ROOT / f"modules/{module}/schema.sql"] = "-- Generated by implementation/postgres/render.py; edit model.py.\n" + "".join(ddl(e) for e in ENTITIES if e.schema == module)
    files[EXAMPLE / "registration.sql"] = "-- Generated deployment-time metadata; edit render.py.\n" + registration() + documentation()
    build = "-- Generated portable example. Run only in a new empty product database.\nBEGIN TRANSACTION;\nCREATE EXTENSION IF NOT EXISTS btree_gist;\nSET TimeZone='UTC';\n"
    build += "\n".join(f"CREATE SCHEMA {m};" for m in MODULES) + "\n"
    for module in ("memory", "semantic", "domain", "observability", "search", "prediction"):
        build += files[ROOT / f"modules/{module}/schema.sql"]
    for path in [ROOT / "modules/search/functions.sql", ROOT / "modules/semantic/discovery.sql",
                 ROOT / "patterns/validation/views.sql", EXAMPLE / "seed.sql"]:
        build += path.read_text(encoding="utf-8") + "\n"
    build += files[EXAMPLE / "registration.sql"]
    # The observations are synthetic historical facts; physical audit time is
    # the actual deployment transaction, never the fixture's business clock.
    build += "-- Record actual physical deployment audit instants.\n"
    build += "\n".join(f"UPDATE {e.qualified} SET created_dts=current_timestamp,updated_dts=current_timestamp;" for e in ENTITIES)
    build += (ROOT / "patterns/access-layer/grants.sql").read_text(encoding="utf-8")
    build += "\nCOMMIT;\n"
    files[EXAMPLE / "build.sql"] = build
    from checks import profile
    files[ROOT / "patterns/validation/conformance.sql"] = (
        "-- Generated from checks.py; read-only violations counts. Zero is pass.\n" +
        "\n".join(f"SELECT {literal(c.test_id)} AS test_id, count(*) AS violations FROM ({c.sql}) defects;" for c in profile()) + "\n")
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in render_all().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Stale generated SQL: " + ", ".join(stale))


if __name__ == "__main__":
    main()
