-- Generated by implementation/postgres/render.py; edit model.py.
CREATE TABLE memory.module_registry (
    module_name VARCHAR NOT NULL,
    container_name VARCHAR NOT NULL,
    deployment_status VARCHAR NOT NULL,
    module_version VARCHAR NOT NULL,
    module_purpose VARCHAR NOT NULL,
    authored_by VARCHAR NOT NULL,
    source_artifact VARCHAR NOT NULL,
    authored_dts TIMESTAMPTZ NOT NULL,
    valid_from_dts TIMESTAMPTZ NOT NULL,
    valid_to_dts TIMESTAMPTZ NOT NULL,
    is_current BOOLEAN NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    deleted_dts TIMESTAMPTZ,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (module_name, valid_from_dts),
    CHECK (module_name IN ('domain','semantic','search','prediction','observability','memory')),
    CHECK (deployment_status IN ('DEPLOYED','PLANNED','DEPRECATED')),
    CHECK(valid_from_dts < valid_to_dts),
    CHECK(is_current = (valid_to_dts = 'infinity'::TIMESTAMPTZ)),
    CHECK(is_deleted = (deleted_dts IS NOT NULL))
);
COMMENT ON TABLE memory.module_registry IS 'Versioned design memory: module registry.';
COMMENT ON COLUMN memory.module_registry.module_name IS 'Module whose design is documented.';
COMMENT ON COLUMN memory.module_registry.container_name IS 'Deployment schema.';
COMMENT ON COLUMN memory.module_registry.deployment_status IS 'Deployment decision.';
COMMENT ON COLUMN memory.module_registry.module_version IS 'Release version.';
COMMENT ON COLUMN memory.module_registry.module_purpose IS 'Why the module is included.';
COMMENT ON COLUMN memory.module_registry.authored_by IS 'Accountable design author.';
COMMENT ON COLUMN memory.module_registry.source_artifact IS 'Source design or deployment artefact.';
COMMENT ON COLUMN memory.module_registry.authored_dts IS 'Instant this documentation revision was authored.';
COMMENT ON COLUMN memory.module_registry.valid_from_dts IS 'Inclusive business validity start.';
COMMENT ON COLUMN memory.module_registry.valid_to_dts IS 'Exclusive business validity end; infinity means open.';
COMMENT ON COLUMN memory.module_registry.is_current IS 'Convenience flag agreeing with the open validity end.';
COMMENT ON COLUMN memory.module_registry.is_deleted IS 'This version records logical deletion; retained for audit.';
COMMENT ON COLUMN memory.module_registry.deleted_dts IS 'Effective deletion instant; null until deletion.';
COMMENT ON COLUMN memory.module_registry.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN memory.module_registry.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW memory.v_module_registry AS SELECT module_name, container_name, deployment_status, module_version, module_purpose, authored_by, source_artifact, authored_dts, valid_from_dts FROM memory.module_registry WHERE is_current AND valid_to_dts='infinity'::TIMESTAMPTZ AND NOT is_deleted;
COMMENT ON VIEW memory.v_module_registry IS 'Consumer contract: Versioned design memory: module registry.';
CREATE FUNCTION memory.at_module_registry(at_dts TIMESTAMPTZ) RETURNS SETOF memory.module_registry LANGUAGE SQL STABLE AS $$ SELECT * FROM memory.module_registry WHERE valid_from_dts <= at_dts AND at_dts < valid_to_dts AND NOT is_deleted; $$;
CREATE UNIQUE INDEX ON memory.module_registry (module_name) WHERE is_current;
ALTER TABLE memory.module_registry ADD EXCLUDE USING gist (module_name WITH =, tstzrange(valid_from_dts, valid_to_dts, '[)') WITH &&);

CREATE TABLE memory.design_decision (
    decision_id VARCHAR NOT NULL,
    decision_version INTEGER NOT NULL,
    decision_title VARCHAR NOT NULL,
    context VARCHAR NOT NULL,
    alternatives VARCHAR NOT NULL,
    rationale VARCHAR NOT NULL,
    consequences VARCHAR NOT NULL,
    decision_status VARCHAR NOT NULL,
    decision_category VARCHAR NOT NULL,
    source_module VARCHAR NOT NULL,
    authored_by VARCHAR NOT NULL,
    source_artifact VARCHAR NOT NULL,
    authored_dts TIMESTAMPTZ NOT NULL,
    valid_from_dts TIMESTAMPTZ NOT NULL,
    valid_to_dts TIMESTAMPTZ NOT NULL,
    is_current BOOLEAN NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    deleted_dts TIMESTAMPTZ,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (decision_id, valid_from_dts),
    CHECK (decision_status IN ('PROPOSED','ACCEPTED','SUPERSEDED','DEPRECATED')),
    CHECK (decision_category IN ('ARCHITECTURE','SCHEMA','NAMING','PERFORMANCE','SECURITY','INTEGRATION','OPERATIONAL')),
    CHECK (source_module IN ('domain','semantic','search','prediction','observability','memory')),
    CHECK(valid_from_dts < valid_to_dts),
    CHECK(is_current = (valid_to_dts = 'infinity'::TIMESTAMPTZ)),
    CHECK(is_deleted = (deleted_dts IS NOT NULL))
);
COMMENT ON TABLE memory.design_decision IS 'Versioned design memory: design decision.';
COMMENT ON COLUMN memory.design_decision.decision_id IS 'Stable decision reference.';
COMMENT ON COLUMN memory.design_decision.decision_version IS 'Decision revision.';
COMMENT ON COLUMN memory.design_decision.decision_title IS 'Question settled.';
COMMENT ON COLUMN memory.design_decision.context IS 'Constraints motivating this decision.';
COMMENT ON COLUMN memory.design_decision.alternatives IS 'Other choices considered.';
COMMENT ON COLUMN memory.design_decision.rationale IS 'Reason for the selected choice.';
COMMENT ON COLUMN memory.design_decision.consequences IS 'Limits and obligations of this choice.';
COMMENT ON COLUMN memory.design_decision.decision_status IS 'Approval state.';
COMMENT ON COLUMN memory.design_decision.decision_category IS 'Decision concern.';
COMMENT ON COLUMN memory.design_decision.source_module IS 'Module whose design this affects.';
COMMENT ON COLUMN memory.design_decision.authored_by IS 'Accountable design author.';
COMMENT ON COLUMN memory.design_decision.source_artifact IS 'Source design or deployment artefact.';
COMMENT ON COLUMN memory.design_decision.authored_dts IS 'Instant this documentation revision was authored.';
COMMENT ON COLUMN memory.design_decision.valid_from_dts IS 'Inclusive business validity start.';
COMMENT ON COLUMN memory.design_decision.valid_to_dts IS 'Exclusive business validity end; infinity means open.';
COMMENT ON COLUMN memory.design_decision.is_current IS 'Convenience flag agreeing with the open validity end.';
COMMENT ON COLUMN memory.design_decision.is_deleted IS 'This version records logical deletion; retained for audit.';
COMMENT ON COLUMN memory.design_decision.deleted_dts IS 'Effective deletion instant; null until deletion.';
COMMENT ON COLUMN memory.design_decision.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN memory.design_decision.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW memory.v_design_decision AS SELECT decision_id, decision_version, decision_title, context, alternatives, rationale, consequences, decision_status, decision_category, source_module, authored_by, source_artifact, authored_dts, valid_from_dts FROM memory.design_decision WHERE is_current AND valid_to_dts='infinity'::TIMESTAMPTZ AND NOT is_deleted;
COMMENT ON VIEW memory.v_design_decision IS 'Consumer contract: Versioned design memory: design decision.';
CREATE FUNCTION memory.at_design_decision(at_dts TIMESTAMPTZ) RETURNS SETOF memory.design_decision LANGUAGE SQL STABLE AS $$ SELECT * FROM memory.design_decision WHERE valid_from_dts <= at_dts AND at_dts < valid_to_dts AND NOT is_deleted; $$;
CREATE UNIQUE INDEX ON memory.design_decision (decision_id) WHERE is_current;
ALTER TABLE memory.design_decision ADD EXCLUDE USING gist (decision_id WITH =, tstzrange(valid_from_dts, valid_to_dts, '[)') WITH &&);

CREATE TABLE memory.business_glossary (
    term VARCHAR NOT NULL,
    term_category VARCHAR NOT NULL,
    definition VARCHAR NOT NULL,
    source_module VARCHAR NOT NULL,
    authored_by VARCHAR NOT NULL,
    source_artifact VARCHAR NOT NULL,
    authored_dts TIMESTAMPTZ NOT NULL,
    valid_from_dts TIMESTAMPTZ NOT NULL,
    valid_to_dts TIMESTAMPTZ NOT NULL,
    is_current BOOLEAN NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    deleted_dts TIMESTAMPTZ,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (term, valid_from_dts),
    CHECK (term_category IN ('ENTITY','ATTRIBUTE','METRIC','BUSINESS_RULE','CLASSIFICATION','REFERENCE_CODE')),
    CHECK (source_module IN ('domain','semantic','search','prediction','observability','memory')),
    CHECK(valid_from_dts < valid_to_dts),
    CHECK(is_current = (valid_to_dts = 'infinity'::TIMESTAMPTZ)),
    CHECK(is_deleted = (deleted_dts IS NOT NULL))
);
COMMENT ON TABLE memory.business_glossary IS 'Versioned design memory: business glossary.';
COMMENT ON COLUMN memory.business_glossary.term IS 'Business term being defined.';
COMMENT ON COLUMN memory.business_glossary.term_category IS 'Kind of term.';
COMMENT ON COLUMN memory.business_glossary.definition IS 'Business definition and usage.';
COMMENT ON COLUMN memory.business_glossary.source_module IS 'Module owning the definition.';
COMMENT ON COLUMN memory.business_glossary.authored_by IS 'Accountable design author.';
COMMENT ON COLUMN memory.business_glossary.source_artifact IS 'Source design or deployment artefact.';
COMMENT ON COLUMN memory.business_glossary.authored_dts IS 'Instant this documentation revision was authored.';
COMMENT ON COLUMN memory.business_glossary.valid_from_dts IS 'Inclusive business validity start.';
COMMENT ON COLUMN memory.business_glossary.valid_to_dts IS 'Exclusive business validity end; infinity means open.';
COMMENT ON COLUMN memory.business_glossary.is_current IS 'Convenience flag agreeing with the open validity end.';
COMMENT ON COLUMN memory.business_glossary.is_deleted IS 'This version records logical deletion; retained for audit.';
COMMENT ON COLUMN memory.business_glossary.deleted_dts IS 'Effective deletion instant; null until deletion.';
COMMENT ON COLUMN memory.business_glossary.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN memory.business_glossary.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW memory.v_business_glossary AS SELECT term, term_category, definition, source_module, authored_by, source_artifact, authored_dts, valid_from_dts FROM memory.business_glossary WHERE is_current AND valid_to_dts='infinity'::TIMESTAMPTZ AND NOT is_deleted;
COMMENT ON VIEW memory.v_business_glossary IS 'Consumer contract: Versioned design memory: business glossary.';
CREATE FUNCTION memory.at_business_glossary(at_dts TIMESTAMPTZ) RETURNS SETOF memory.business_glossary LANGUAGE SQL STABLE AS $$ SELECT * FROM memory.business_glossary WHERE valid_from_dts <= at_dts AND at_dts < valid_to_dts AND NOT is_deleted; $$;
CREATE UNIQUE INDEX ON memory.business_glossary (term) WHERE is_current;
ALTER TABLE memory.business_glossary ADD EXCLUDE USING gist (term WITH =, tstzrange(valid_from_dts, valid_to_dts, '[)') WITH &&);

CREATE TABLE memory.query_cookbook (
    recipe_id VARCHAR NOT NULL,
    recipe_title VARCHAR NOT NULL,
    use_case VARCHAR NOT NULL,
    target_module VARCHAR NOT NULL,
    query_template VARCHAR NOT NULL,
    complexity VARCHAR NOT NULL,
    is_batch BOOLEAN NOT NULL,
    source_module VARCHAR NOT NULL,
    authored_by VARCHAR NOT NULL,
    source_artifact VARCHAR NOT NULL,
    authored_dts TIMESTAMPTZ NOT NULL,
    valid_from_dts TIMESTAMPTZ NOT NULL,
    valid_to_dts TIMESTAMPTZ NOT NULL,
    is_current BOOLEAN NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    deleted_dts TIMESTAMPTZ,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (recipe_id, valid_from_dts),
    CHECK (complexity IN ('SIMPLE','MODERATE','COMPLEX','ADVANCED')),
    CHECK (source_module IN ('domain','semantic','search','prediction','observability','memory')),
    CHECK(valid_from_dts < valid_to_dts),
    CHECK(is_current = (valid_to_dts = 'infinity'::TIMESTAMPTZ)),
    CHECK(is_deleted = (deleted_dts IS NOT NULL))
);
COMMENT ON TABLE memory.query_cookbook IS 'Versioned design memory: query cookbook.';
COMMENT ON COLUMN memory.query_cookbook.recipe_id IS 'Stable recipe identity.';
COMMENT ON COLUMN memory.query_cookbook.recipe_title IS 'Question the recipe answers.';
COMMENT ON COLUMN memory.query_cookbook.use_case IS 'Intended consumer use.';
COMMENT ON COLUMN memory.query_cookbook.target_module IS 'Module or CROSS composition.';
COMMENT ON COLUMN memory.query_cookbook.query_template IS 'Executable PostgreSQL SQL, never result data.';
COMMENT ON COLUMN memory.query_cookbook.complexity IS 'Expected query complexity.';
COMMENT ON COLUMN memory.query_cookbook.is_batch IS 'Whether intended for batch only.';
COMMENT ON COLUMN memory.query_cookbook.source_module IS 'Module responsible for recipe correctness.';
COMMENT ON COLUMN memory.query_cookbook.authored_by IS 'Accountable design author.';
COMMENT ON COLUMN memory.query_cookbook.source_artifact IS 'Source design or deployment artefact.';
COMMENT ON COLUMN memory.query_cookbook.authored_dts IS 'Instant this documentation revision was authored.';
COMMENT ON COLUMN memory.query_cookbook.valid_from_dts IS 'Inclusive business validity start.';
COMMENT ON COLUMN memory.query_cookbook.valid_to_dts IS 'Exclusive business validity end; infinity means open.';
COMMENT ON COLUMN memory.query_cookbook.is_current IS 'Convenience flag agreeing with the open validity end.';
COMMENT ON COLUMN memory.query_cookbook.is_deleted IS 'This version records logical deletion; retained for audit.';
COMMENT ON COLUMN memory.query_cookbook.deleted_dts IS 'Effective deletion instant; null until deletion.';
COMMENT ON COLUMN memory.query_cookbook.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN memory.query_cookbook.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW memory.v_query_cookbook AS SELECT recipe_id, recipe_title, use_case, target_module, query_template, complexity, is_batch, source_module, authored_by, source_artifact, authored_dts, valid_from_dts FROM memory.query_cookbook WHERE is_current AND valid_to_dts='infinity'::TIMESTAMPTZ AND NOT is_deleted;
COMMENT ON VIEW memory.v_query_cookbook IS 'Consumer contract: Versioned design memory: query cookbook.';
CREATE FUNCTION memory.at_query_cookbook(at_dts TIMESTAMPTZ) RETURNS SETOF memory.query_cookbook LANGUAGE SQL STABLE AS $$ SELECT * FROM memory.query_cookbook WHERE valid_from_dts <= at_dts AND at_dts < valid_to_dts AND NOT is_deleted; $$;
CREATE UNIQUE INDEX ON memory.query_cookbook (recipe_id) WHERE is_current;
ALTER TABLE memory.query_cookbook ADD EXCLUDE USING gist (recipe_id WITH =, tstzrange(valid_from_dts, valid_to_dts, '[)') WITH &&);

CREATE TABLE memory.implementation_note (
    note_id VARCHAR NOT NULL,
    note_title VARCHAR NOT NULL,
    note_content VARCHAR NOT NULL,
    note_category VARCHAR NOT NULL,
    source_module VARCHAR NOT NULL,
    authored_by VARCHAR NOT NULL,
    source_artifact VARCHAR NOT NULL,
    authored_dts TIMESTAMPTZ NOT NULL,
    valid_from_dts TIMESTAMPTZ NOT NULL,
    valid_to_dts TIMESTAMPTZ NOT NULL,
    is_current BOOLEAN NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    deleted_dts TIMESTAMPTZ,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (note_id, valid_from_dts),
    CHECK (source_module IN ('domain','semantic','search','prediction','observability','memory')),
    CHECK(valid_from_dts < valid_to_dts),
    CHECK(is_current = (valid_to_dts = 'infinity'::TIMESTAMPTZ)),
    CHECK(is_deleted = (deleted_dts IS NOT NULL))
);
COMMENT ON TABLE memory.implementation_note IS 'Versioned design memory: implementation note.';
COMMENT ON COLUMN memory.implementation_note.note_id IS 'Stable operational note identity.';
COMMENT ON COLUMN memory.implementation_note.note_title IS 'Operational concern.';
COMMENT ON COLUMN memory.implementation_note.note_content IS 'How to operate within this constraint.';
COMMENT ON COLUMN memory.implementation_note.note_category IS 'Type of guidance.';
COMMENT ON COLUMN memory.implementation_note.source_module IS 'Module affected.';
COMMENT ON COLUMN memory.implementation_note.authored_by IS 'Accountable design author.';
COMMENT ON COLUMN memory.implementation_note.source_artifact IS 'Source design or deployment artefact.';
COMMENT ON COLUMN memory.implementation_note.authored_dts IS 'Instant this documentation revision was authored.';
COMMENT ON COLUMN memory.implementation_note.valid_from_dts IS 'Inclusive business validity start.';
COMMENT ON COLUMN memory.implementation_note.valid_to_dts IS 'Exclusive business validity end; infinity means open.';
COMMENT ON COLUMN memory.implementation_note.is_current IS 'Convenience flag agreeing with the open validity end.';
COMMENT ON COLUMN memory.implementation_note.is_deleted IS 'This version records logical deletion; retained for audit.';
COMMENT ON COLUMN memory.implementation_note.deleted_dts IS 'Effective deletion instant; null until deletion.';
COMMENT ON COLUMN memory.implementation_note.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN memory.implementation_note.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW memory.v_implementation_note AS SELECT note_id, note_title, note_content, note_category, source_module, authored_by, source_artifact, authored_dts, valid_from_dts FROM memory.implementation_note WHERE is_current AND valid_to_dts='infinity'::TIMESTAMPTZ AND NOT is_deleted;
COMMENT ON VIEW memory.v_implementation_note IS 'Consumer contract: Versioned design memory: implementation note.';
CREATE FUNCTION memory.at_implementation_note(at_dts TIMESTAMPTZ) RETURNS SETOF memory.implementation_note LANGUAGE SQL STABLE AS $$ SELECT * FROM memory.implementation_note WHERE valid_from_dts <= at_dts AND at_dts < valid_to_dts AND NOT is_deleted; $$;
CREATE UNIQUE INDEX ON memory.implementation_note (note_id) WHERE is_current;
ALTER TABLE memory.implementation_note ADD EXCLUDE USING gist (note_id WITH =, tstzrange(valid_from_dts, valid_to_dts, '[)') WITH &&);

CREATE TABLE memory.change_log (
    change_id VARCHAR NOT NULL,
    version_number VARCHAR NOT NULL,
    change_title VARCHAR NOT NULL,
    change_type VARCHAR NOT NULL,
    source_module VARCHAR NOT NULL,
    related_decision_id VARCHAR NOT NULL,
    authored_by VARCHAR NOT NULL,
    source_artifact VARCHAR NOT NULL,
    authored_dts TIMESTAMPTZ NOT NULL,
    valid_from_dts TIMESTAMPTZ NOT NULL,
    valid_to_dts TIMESTAMPTZ NOT NULL,
    is_current BOOLEAN NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    deleted_dts TIMESTAMPTZ,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (change_id, valid_from_dts),
    CHECK (source_module IN ('domain','semantic','search','prediction','observability','memory')),
    CHECK(valid_from_dts < valid_to_dts),
    CHECK(is_current = (valid_to_dts = 'infinity'::TIMESTAMPTZ)),
    CHECK(is_deleted = (deleted_dts IS NOT NULL))
);
COMMENT ON TABLE memory.change_log IS 'Versioned design memory: change log.';
COMMENT ON COLUMN memory.change_log.change_id IS 'Stable change identity.';
COMMENT ON COLUMN memory.change_log.version_number IS 'Product release.';
COMMENT ON COLUMN memory.change_log.change_title IS 'What changed and why.';
COMMENT ON COLUMN memory.change_log.change_type IS 'Release change category.';
COMMENT ON COLUMN memory.change_log.source_module IS 'Module affected.';
COMMENT ON COLUMN memory.change_log.related_decision_id IS 'Decision explaining the change.';
COMMENT ON COLUMN memory.change_log.authored_by IS 'Accountable design author.';
COMMENT ON COLUMN memory.change_log.source_artifact IS 'Source design or deployment artefact.';
COMMENT ON COLUMN memory.change_log.authored_dts IS 'Instant this documentation revision was authored.';
COMMENT ON COLUMN memory.change_log.valid_from_dts IS 'Inclusive business validity start.';
COMMENT ON COLUMN memory.change_log.valid_to_dts IS 'Exclusive business validity end; infinity means open.';
COMMENT ON COLUMN memory.change_log.is_current IS 'Convenience flag agreeing with the open validity end.';
COMMENT ON COLUMN memory.change_log.is_deleted IS 'This version records logical deletion; retained for audit.';
COMMENT ON COLUMN memory.change_log.deleted_dts IS 'Effective deletion instant; null until deletion.';
COMMENT ON COLUMN memory.change_log.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN memory.change_log.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW memory.v_change_log AS SELECT change_id, version_number, change_title, change_type, source_module, related_decision_id, authored_by, source_artifact, authored_dts, valid_from_dts FROM memory.change_log WHERE is_current AND valid_to_dts='infinity'::TIMESTAMPTZ AND NOT is_deleted;
COMMENT ON VIEW memory.v_change_log IS 'Consumer contract: Versioned design memory: change log.';
CREATE FUNCTION memory.at_change_log(at_dts TIMESTAMPTZ) RETURNS SETOF memory.change_log LANGUAGE SQL STABLE AS $$ SELECT * FROM memory.change_log WHERE valid_from_dts <= at_dts AND at_dts < valid_to_dts AND NOT is_deleted; $$;
CREATE UNIQUE INDEX ON memory.change_log (change_id) WHERE is_current;
ALTER TABLE memory.change_log ADD EXCLUDE USING gist (change_id WITH =, tstzrange(valid_from_dts, valid_to_dts, '[)') WITH &&);

CREATE TABLE memory.agent_session (
    session_id BIGINT NOT NULL,
    session_key VARCHAR NOT NULL,
    agent_key VARCHAR NOT NULL,
    user_key VARCHAR NOT NULL,
    session_start_dts TIMESTAMPTZ NOT NULL,
    session_end_dts TIMESTAMPTZ,
    session_status VARCHAR NOT NULL,
    session_goal VARCHAR NOT NULL,
    session_context JSONB,
    scope_level VARCHAR NOT NULL CHECK (scope_level IN ('USER','TEAM','ORGANIZATION','AGENT')),
    scope_identifier VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (session_id),
    CHECK (session_status IN ('ACTIVE','COMPLETED','ABANDONED')),
    CHECK (scope_level IN ('USER','TEAM','ORGANIZATION','AGENT'))
);
COMMENT ON TABLE memory.agent_session IS 'Private runtime process metadata: agent session.';
COMMENT ON COLUMN memory.agent_session.session_id IS 'Stable surrogate identifying session; never recycled.';
COMMENT ON COLUMN memory.agent_session.session_key IS 'External session identity.';
COMMENT ON COLUMN memory.agent_session.agent_key IS 'Executing agent.';
COMMENT ON COLUMN memory.agent_session.user_key IS 'Pseudonymous user identity.';
COMMENT ON COLUMN memory.agent_session.session_start_dts IS 'Session start.';
COMMENT ON COLUMN memory.agent_session.session_end_dts IS 'Session end; null while active.';
COMMENT ON COLUMN memory.agent_session.session_status IS 'ACTIVE, COMPLETED or ABANDONED.';
COMMENT ON COLUMN memory.agent_session.session_goal IS 'Process goal, never query results.';
COMMENT ON COLUMN memory.agent_session.session_context IS 'Process context only.';
COMMENT ON COLUMN memory.agent_session.scope_level IS 'Privacy scope; USER ownership is checked against authenticated session_user.';
COMMENT ON COLUMN memory.agent_session.scope_identifier IS 'Owner identity within the declared privacy boundary.';
COMMENT ON COLUMN memory.agent_session.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN memory.agent_session.updated_dts IS 'Instant this physical row was last changed.';

CREATE TABLE memory.agent_interaction (
    interaction_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    interaction_seq INTEGER NOT NULL,
    interaction_dts TIMESTAMPTZ NOT NULL,
    interaction_type VARCHAR NOT NULL,
    referenced_tables VARCHAR NOT NULL,
    query_executed VARCHAR NOT NULL,
    query_result_count INTEGER,
    outcome_status VARCHAR NOT NULL,
    scope_level VARCHAR NOT NULL CHECK (scope_level IN ('USER','TEAM','ORGANIZATION','AGENT')),
    scope_identifier VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (interaction_id),
    CHECK (interaction_type IN ('QUERY','ACTION','DECISION','EXPLANATION')),
    CHECK (outcome_status IN ('SUCCESS','PARTIAL','FAILED')),
    CHECK (scope_level IN ('USER','TEAM','ORGANIZATION','AGENT'))
);
COMMENT ON TABLE memory.agent_interaction IS 'Private runtime process metadata: agent interaction.';
COMMENT ON COLUMN memory.agent_interaction.interaction_id IS 'Stable surrogate identifying interaction; never recycled.';
COMMENT ON COLUMN memory.agent_interaction.session_id IS 'Stable surrogate identifying memory.agent_session; never recycled.';
COMMENT ON COLUMN memory.agent_interaction.interaction_seq IS 'Ordering within session.';
COMMENT ON COLUMN memory.agent_interaction.interaction_dts IS 'Interaction occurred.';
COMMENT ON COLUMN memory.agent_interaction.interaction_type IS 'QUERY, ACTION, DECISION or EXPLANATION.';
COMMENT ON COLUMN memory.agent_interaction.referenced_tables IS 'Table-level references only.';
COMMENT ON COLUMN memory.agent_interaction.query_executed IS 'SQL performed; parameter values must be redacted.';
COMMENT ON COLUMN memory.agent_interaction.query_result_count IS 'Aggregate result count only.';
COMMENT ON COLUMN memory.agent_interaction.outcome_status IS 'Execution result status.';
COMMENT ON COLUMN memory.agent_interaction.scope_level IS 'Privacy scope; USER ownership is checked against authenticated session_user.';
COMMENT ON COLUMN memory.agent_interaction.scope_identifier IS 'Owner identity within the declared privacy boundary.';
COMMENT ON COLUMN memory.agent_interaction.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN memory.agent_interaction.updated_dts IS 'Instant this physical row was last changed.';

CREATE TABLE memory.learned_strategy (
    strategy_id BIGINT NOT NULL,
    strategy_name VARCHAR NOT NULL,
    strategy_category VARCHAR NOT NULL,
    strategy_pattern VARCHAR NOT NULL,
    success_rate DECIMAL(5,4) CHECK(success_rate BETWEEN 0 AND 1),
    times_used INTEGER,
    is_validated BOOLEAN NOT NULL,
    scope_level VARCHAR NOT NULL CHECK (scope_level IN ('USER','TEAM','ORGANIZATION','AGENT')),
    scope_identifier VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (strategy_id),
    CHECK (scope_level IN ('USER','TEAM','ORGANIZATION','AGENT'))
);
COMMENT ON TABLE memory.learned_strategy IS 'Private runtime process metadata: learned strategy.';
COMMENT ON COLUMN memory.learned_strategy.strategy_id IS 'Stable surrogate identifying strategy; never recycled.';
COMMENT ON COLUMN memory.learned_strategy.strategy_name IS 'Reusable process strategy.';
COMMENT ON COLUMN memory.learned_strategy.strategy_category IS 'Type of process learning.';
COMMENT ON COLUMN memory.learned_strategy.strategy_pattern IS 'Approach, without business content.';
COMMENT ON COLUMN memory.learned_strategy.success_rate IS 'Observed success fraction.';
COMMENT ON COLUMN memory.learned_strategy.times_used IS 'Observed usage count.';
COMMENT ON COLUMN memory.learned_strategy.is_validated IS 'Whether strategy has supporting evidence.';
COMMENT ON COLUMN memory.learned_strategy.scope_level IS 'Privacy scope; USER ownership is checked against authenticated session_user.';
COMMENT ON COLUMN memory.learned_strategy.scope_identifier IS 'Owner identity within the declared privacy boundary.';
COMMENT ON COLUMN memory.learned_strategy.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN memory.learned_strategy.updated_dts IS 'Instant this physical row was last changed.';

CREATE TABLE memory.user_preference (
    preference_id BIGINT NOT NULL,
    user_key VARCHAR NOT NULL,
    preference_category VARCHAR NOT NULL,
    preference_name VARCHAR NOT NULL,
    preference_value VARCHAR NOT NULL,
    scope_level VARCHAR NOT NULL CHECK (scope_level IN ('USER','TEAM','ORGANIZATION','AGENT')),
    scope_identifier VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (preference_id),
    CHECK (scope_level IN ('USER','TEAM','ORGANIZATION','AGENT'))
);
COMMENT ON TABLE memory.user_preference IS 'Private runtime process metadata: user preference.';
COMMENT ON COLUMN memory.user_preference.preference_id IS 'Stable surrogate identifying preference; never recycled.';
COMMENT ON COLUMN memory.user_preference.user_key IS 'Pseudonymous preference owner.';
COMMENT ON COLUMN memory.user_preference.preference_category IS 'Presentation or analysis preference kind.';
COMMENT ON COLUMN memory.user_preference.preference_name IS 'Preference setting.';
COMMENT ON COLUMN memory.user_preference.preference_value IS 'Preference value, never Domain content.';
COMMENT ON COLUMN memory.user_preference.scope_level IS 'Privacy scope; USER ownership is checked against authenticated session_user.';
COMMENT ON COLUMN memory.user_preference.scope_identifier IS 'Owner identity within the declared privacy boundary.';
COMMENT ON COLUMN memory.user_preference.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN memory.user_preference.updated_dts IS 'Instant this physical row was last changed.';

CREATE TABLE memory.discovered_pattern (
    pattern_id BIGINT NOT NULL,
    pattern_name VARCHAR NOT NULL,
    pattern_type VARCHAR NOT NULL,
    pattern_definition JSONB,
    sample_size INTEGER,
    involved_tables VARCHAR NOT NULL,
    is_validated BOOLEAN NOT NULL,
    scope_level VARCHAR NOT NULL CHECK (scope_level IN ('USER','TEAM','ORGANIZATION','AGENT')),
    scope_identifier VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (pattern_id),
    CHECK (scope_level IN ('USER','TEAM','ORGANIZATION','AGENT'))
);
COMMENT ON TABLE memory.discovered_pattern IS 'Private runtime process metadata: discovered pattern.';
COMMENT ON COLUMN memory.discovered_pattern.pattern_id IS 'Stable surrogate identifying pattern; never recycled.';
COMMENT ON COLUMN memory.discovered_pattern.pattern_name IS 'Observed process pattern.';
COMMENT ON COLUMN memory.discovered_pattern.pattern_type IS 'Pattern class.';
COMMENT ON COLUMN memory.discovered_pattern.pattern_definition IS 'Table-level pattern metadata.';
COMMENT ON COLUMN memory.discovered_pattern.sample_size IS 'Aggregate count analysed.';
COMMENT ON COLUMN memory.discovered_pattern.involved_tables IS 'Table-level references only.';
COMMENT ON COLUMN memory.discovered_pattern.is_validated IS 'Whether evidence supports the pattern.';
COMMENT ON COLUMN memory.discovered_pattern.scope_level IS 'Privacy scope; USER ownership is checked against authenticated session_user.';
COMMENT ON COLUMN memory.discovered_pattern.scope_identifier IS 'Owner identity within the declared privacy boundary.';
COMMENT ON COLUMN memory.discovered_pattern.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN memory.discovered_pattern.updated_dts IS 'Instant this physical row was last changed.';

