-- Generated by implementation/duckdb/render.py; edit model.py.
CREATE TABLE domain.customer_keymap (
    customer_id BIGINT NOT NULL,
    customer_key VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (customer_id),
    UNIQUE (customer_key)
);
COMMENT ON TABLE domain.customer_keymap IS 'Permanent natural-key allocation for customer.';
COMMENT ON COLUMN domain.customer_keymap.customer_id IS 'Stable surrogate identifying customer; never recycled.';
COMMENT ON COLUMN domain.customer_keymap.customer_key IS 'Immutable originating-system business identifier.';
COMMENT ON COLUMN domain.customer_keymap.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN domain.customer_keymap.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW domain.v_customer_keymap AS SELECT customer_id, customer_key FROM domain.customer_keymap;
COMMENT ON VIEW domain.v_customer_keymap IS 'Consumer contract: Permanent natural-key allocation for customer.';

CREATE TABLE domain.customer (
    customer_id BIGINT NOT NULL,
    customer_key VARCHAR NOT NULL,
    display_name VARCHAR NOT NULL,
    segment VARCHAR NOT NULL,
    valid_from_dts TIMESTAMPTZ NOT NULL,
    valid_to_dts TIMESTAMPTZ NOT NULL,
    is_current BOOLEAN NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    deleted_dts TIMESTAMPTZ,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (customer_id, valid_from_dts),
    CHECK(valid_from_dts < valid_to_dts),
    CHECK(is_current = (valid_to_dts = 'infinity'::TIMESTAMPTZ)),
    CHECK(is_deleted = (deleted_dts IS NOT NULL))
);
COMMENT ON TABLE domain.customer IS 'Authoritative synthetic customer identity and segment history.';
COMMENT ON COLUMN domain.customer.customer_id IS 'Stable surrogate identifying customer; never recycled.';
COMMENT ON COLUMN domain.customer.customer_key IS 'Originating-system business identifier.';
COMMENT ON COLUMN domain.customer.display_name IS 'Synthetic customer display name; never copied to enhancement tables.';
COMMENT ON COLUMN domain.customer.segment IS 'Customer service segment assigned by the source.';
COMMENT ON COLUMN domain.customer.valid_from_dts IS 'Inclusive business validity start.';
COMMENT ON COLUMN domain.customer.valid_to_dts IS 'Exclusive business validity end; infinity means open.';
COMMENT ON COLUMN domain.customer.is_current IS 'Convenience flag agreeing with the open validity end.';
COMMENT ON COLUMN domain.customer.is_deleted IS 'This version records logical deletion; retained for audit.';
COMMENT ON COLUMN domain.customer.deleted_dts IS 'Effective deletion instant; null until deletion.';
COMMENT ON COLUMN domain.customer.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN domain.customer.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW domain.v_customer AS SELECT customer_id, customer_key, display_name, segment, valid_from_dts FROM domain.customer WHERE is_current AND valid_to_dts='infinity'::TIMESTAMPTZ AND NOT is_deleted;
COMMENT ON VIEW domain.v_customer IS 'Consumer contract: Authoritative synthetic customer identity and segment history.';
CREATE MACRO domain.at_customer(at_dts) AS TABLE SELECT customer_id, customer_key, display_name, segment, valid_from_dts, valid_to_dts, is_current, is_deleted, deleted_dts, created_dts, updated_dts FROM domain.customer WHERE valid_from_dts <= at_dts::TIMESTAMPTZ AND at_dts::TIMESTAMPTZ < valid_to_dts AND NOT is_deleted;

CREATE TABLE domain.product_keymap (
    product_id BIGINT NOT NULL,
    product_key VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (product_id),
    UNIQUE (product_key)
);
COMMENT ON TABLE domain.product_keymap IS 'Permanent natural-key allocation for product.';
COMMENT ON COLUMN domain.product_keymap.product_id IS 'Stable surrogate identifying product; never recycled.';
COMMENT ON COLUMN domain.product_keymap.product_key IS 'Immutable originating-system business identifier.';
COMMENT ON COLUMN domain.product_keymap.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN domain.product_keymap.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW domain.v_product_keymap AS SELECT product_id, product_key FROM domain.product_keymap;
COMMENT ON VIEW domain.v_product_keymap IS 'Consumer contract: Permanent natural-key allocation for product.';

CREATE TABLE domain.product (
    product_id BIGINT NOT NULL,
    product_key VARCHAR NOT NULL,
    product_name VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    valid_from_dts TIMESTAMPTZ NOT NULL,
    valid_to_dts TIMESTAMPTZ NOT NULL,
    is_current BOOLEAN NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    deleted_dts TIMESTAMPTZ,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (product_id, valid_from_dts),
    CHECK(valid_from_dts < valid_to_dts),
    CHECK(is_current = (valid_to_dts = 'infinity'::TIMESTAMPTZ)),
    CHECK(is_deleted = (deleted_dts IS NOT NULL))
);
COMMENT ON TABLE domain.product IS 'Financial offering reference set, versioned when its meaning changes.';
COMMENT ON COLUMN domain.product.product_id IS 'Stable surrogate identifying product; never recycled.';
COMMENT ON COLUMN domain.product.product_key IS 'Originating-system business identifier.';
COMMENT ON COLUMN domain.product.product_name IS 'Human-facing name of the financial offering.';
COMMENT ON COLUMN domain.product.description IS 'Authoritative description used for retrieval.';
COMMENT ON COLUMN domain.product.valid_from_dts IS 'Inclusive business validity start.';
COMMENT ON COLUMN domain.product.valid_to_dts IS 'Exclusive business validity end; infinity means open.';
COMMENT ON COLUMN domain.product.is_current IS 'Convenience flag agreeing with the open validity end.';
COMMENT ON COLUMN domain.product.is_deleted IS 'This version records logical deletion; retained for audit.';
COMMENT ON COLUMN domain.product.deleted_dts IS 'Effective deletion instant; null until deletion.';
COMMENT ON COLUMN domain.product.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN domain.product.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW domain.v_product AS SELECT product_id, product_key, product_name, description, valid_from_dts FROM domain.product WHERE is_current AND valid_to_dts='infinity'::TIMESTAMPTZ AND NOT is_deleted;
COMMENT ON VIEW domain.v_product IS 'Consumer contract: Financial offering reference set, versioned when its meaning changes.';
CREATE MACRO domain.at_product(at_dts) AS TABLE SELECT product_id, product_key, product_name, description, valid_from_dts, valid_to_dts, is_current, is_deleted, deleted_dts, created_dts, updated_dts FROM domain.product WHERE valid_from_dts <= at_dts::TIMESTAMPTZ AND at_dts::TIMESTAMPTZ < valid_to_dts AND NOT is_deleted;

CREATE TABLE domain.account_keymap (
    account_id BIGINT NOT NULL,
    account_key VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (account_id),
    UNIQUE (account_key)
);
COMMENT ON TABLE domain.account_keymap IS 'Permanent natural-key allocation for account.';
COMMENT ON COLUMN domain.account_keymap.account_id IS 'Stable surrogate identifying account; never recycled.';
COMMENT ON COLUMN domain.account_keymap.account_key IS 'Immutable originating-system business identifier.';
COMMENT ON COLUMN domain.account_keymap.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN domain.account_keymap.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW domain.v_account_keymap AS SELECT account_id, account_key FROM domain.account_keymap;
COMMENT ON VIEW domain.v_account_keymap IS 'Consumer contract: Permanent natural-key allocation for account.';

CREATE TABLE domain.account (
    account_id BIGINT NOT NULL,
    account_key VARCHAR NOT NULL,
    customer_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    valid_from_dts TIMESTAMPTZ NOT NULL,
    valid_to_dts TIMESTAMPTZ NOT NULL,
    is_current BOOLEAN NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    deleted_dts TIMESTAMPTZ,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (account_id, valid_from_dts),
    CHECK(valid_from_dts < valid_to_dts),
    CHECK(is_current = (valid_to_dts = 'infinity'::TIMESTAMPTZ)),
    CHECK(is_deleted = (deleted_dts IS NOT NULL))
);
COMMENT ON TABLE domain.account IS 'Account ownership and offering history; connects customers to products.';
COMMENT ON COLUMN domain.account.account_id IS 'Stable surrogate identifying account; never recycled.';
COMMENT ON COLUMN domain.account.account_key IS 'Originating-system business identifier.';
COMMENT ON COLUMN domain.account.customer_id IS 'Stable surrogate identifying domain.customer; never recycled.';
COMMENT ON COLUMN domain.account.product_id IS 'Stable surrogate identifying domain.product; never recycled.';
COMMENT ON COLUMN domain.account.valid_from_dts IS 'Inclusive business validity start.';
COMMENT ON COLUMN domain.account.valid_to_dts IS 'Exclusive business validity end; infinity means open.';
COMMENT ON COLUMN domain.account.is_current IS 'Convenience flag agreeing with the open validity end.';
COMMENT ON COLUMN domain.account.is_deleted IS 'This version records logical deletion; retained for audit.';
COMMENT ON COLUMN domain.account.deleted_dts IS 'Effective deletion instant; null until deletion.';
COMMENT ON COLUMN domain.account.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN domain.account.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW domain.v_account AS SELECT account_id, account_key, customer_id, product_id, valid_from_dts FROM domain.account WHERE is_current AND valid_to_dts='infinity'::TIMESTAMPTZ AND NOT is_deleted;
COMMENT ON VIEW domain.v_account IS 'Consumer contract: Account ownership and offering history; connects customers to products.';
CREATE MACRO domain.at_account(at_dts) AS TABLE SELECT account_id, account_key, customer_id, product_id, valid_from_dts, valid_to_dts, is_current, is_deleted, deleted_dts, created_dts, updated_dts FROM domain.account WHERE valid_from_dts <= at_dts::TIMESTAMPTZ AND at_dts::TIMESTAMPTZ < valid_to_dts AND NOT is_deleted;

CREATE TABLE domain.transaction_keymap (
    transaction_id BIGINT NOT NULL,
    transaction_key VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (transaction_id),
    UNIQUE (transaction_key)
);
COMMENT ON TABLE domain.transaction_keymap IS 'Permanent natural-key allocation for transaction.';
COMMENT ON COLUMN domain.transaction_keymap.transaction_id IS 'Stable surrogate identifying transaction; never recycled.';
COMMENT ON COLUMN domain.transaction_keymap.transaction_key IS 'Immutable originating-system business identifier.';
COMMENT ON COLUMN domain.transaction_keymap.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN domain.transaction_keymap.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW domain.v_transaction_keymap AS SELECT transaction_id, transaction_key FROM domain.transaction_keymap;
COMMENT ON VIEW domain.v_transaction_keymap IS 'Consumer contract: Permanent natural-key allocation for transaction.';

CREATE TABLE domain.transaction (
    transaction_id BIGINT NOT NULL,
    transaction_key VARCHAR NOT NULL,
    account_id BIGINT NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    posted_dts TIMESTAMPTZ NOT NULL,
    valid_from_dts TIMESTAMPTZ NOT NULL,
    valid_to_dts TIMESTAMPTZ NOT NULL,
    is_current BOOLEAN NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    deleted_dts TIMESTAMPTZ,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (transaction_id, valid_from_dts),
    CHECK(valid_from_dts < valid_to_dts),
    CHECK(is_current = (valid_to_dts = 'infinity'::TIMESTAMPTZ)),
    CHECK(is_deleted = (deleted_dts IS NOT NULL))
);
COMMENT ON TABLE domain.transaction IS 'Authoritative posted transactions, with correction history.';
COMMENT ON COLUMN domain.transaction.transaction_id IS 'Stable surrogate identifying transaction; never recycled.';
COMMENT ON COLUMN domain.transaction.transaction_key IS 'Originating-system business identifier.';
COMMENT ON COLUMN domain.transaction.account_id IS 'Stable surrogate identifying domain.account; never recycled.';
COMMENT ON COLUMN domain.transaction.amount IS 'Signed transaction amount in AUD.';
COMMENT ON COLUMN domain.transaction.posted_dts IS 'Instant the source posted the transaction.';
COMMENT ON COLUMN domain.transaction.valid_from_dts IS 'Inclusive business validity start.';
COMMENT ON COLUMN domain.transaction.valid_to_dts IS 'Exclusive business validity end; infinity means open.';
COMMENT ON COLUMN domain.transaction.is_current IS 'Convenience flag agreeing with the open validity end.';
COMMENT ON COLUMN domain.transaction.is_deleted IS 'This version records logical deletion; retained for audit.';
COMMENT ON COLUMN domain.transaction.deleted_dts IS 'Effective deletion instant; null until deletion.';
COMMENT ON COLUMN domain.transaction.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN domain.transaction.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW domain.v_transaction AS SELECT transaction_id, transaction_key, account_id, amount, posted_dts, valid_from_dts FROM domain.transaction WHERE is_current AND valid_to_dts='infinity'::TIMESTAMPTZ AND NOT is_deleted;
COMMENT ON VIEW domain.v_transaction IS 'Consumer contract: Authoritative posted transactions, with correction history.';
CREATE MACRO domain.at_transaction(at_dts) AS TABLE SELECT transaction_id, transaction_key, account_id, amount, posted_dts, valid_from_dts, valid_to_dts, is_current, is_deleted, deleted_dts, created_dts, updated_dts FROM domain.transaction WHERE valid_from_dts <= at_dts::TIMESTAMPTZ AND at_dts::TIMESTAMPTZ < valid_to_dts AND NOT is_deleted;

