-- Generated by implementation/postgres/render.py; edit model.py.
CREATE TABLE search.entity_embedding (
    embedding_id BIGINT NOT NULL,
    entity_id BIGINT NOT NULL,
    entity_kind VARCHAR NOT NULL CHECK(entity_kind='PRODUCT'),
    source_module VARCHAR NOT NULL,
    source_attribute VARCHAR NOT NULL,
    embedding DOUBLE PRECISION[] NOT NULL,
    embedding_dimensions INTEGER NOT NULL CHECK(embedding_dimensions=3),
    embedding_model VARCHAR NOT NULL,
    embedding_model_version VARCHAR NOT NULL,
    generated_dts TIMESTAMPTZ NOT NULL,
    computation_method VARCHAR NOT NULL,
    valid_from_dts TIMESTAMPTZ NOT NULL,
    valid_to_dts TIMESTAMPTZ NOT NULL,
    is_current BOOLEAN NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    deleted_dts TIMESTAMPTZ,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    CHECK (array_ndims(embedding)=1 AND array_lower(embedding,1)=1 AND cardinality(embedding)=embedding_dimensions AND array_position(embedding,NULL) IS NULL),
    PRIMARY KEY (embedding_id, valid_from_dts),
    CHECK (source_module IN ('domain','semantic','search','prediction','observability','memory')),
    CHECK(valid_from_dts < valid_to_dts),
    CHECK(is_current = (valid_to_dts = 'infinity'::TIMESTAMPTZ)),
    CHECK(is_deleted = (deleted_dts IS NOT NULL))
);
COMMENT ON TABLE search.entity_embedding IS 'Versioned vectors and identifiers; content obtained by Domain join-back.';
COMMENT ON COLUMN search.entity_embedding.embedding_id IS 'Stable surrogate identifying embedding; never recycled.';
COMMENT ON COLUMN search.entity_embedding.entity_id IS 'Stable surrogate identifying domain.product; never recycled.';
COMMENT ON COLUMN search.entity_embedding.entity_kind IS 'Generic reference discriminator.';
COMMENT ON COLUMN search.entity_embedding.source_module IS 'Owner of authoritative input.';
COMMENT ON COLUMN search.entity_embedding.source_attribute IS 'Attribute encoded by the model.';
COMMENT ON COLUMN search.entity_embedding.embedding IS 'Synthetic three-axis vector; not a general semantic language model.';
COMMENT ON COLUMN search.entity_embedding.embedding_dimensions IS 'Fixed dimensionality for this model family.';
COMMENT ON COLUMN search.entity_embedding.embedding_model IS 'Registered embedding model key.';
COMMENT ON COLUMN search.entity_embedding.embedding_model_version IS 'Producer model version.';
COMMENT ON COLUMN search.entity_embedding.generated_dts IS 'When vector was computed.';
COMMENT ON COLUMN search.entity_embedding.computation_method IS 'IN_DATABASE toy lexical encoder.';
COMMENT ON COLUMN search.entity_embedding.valid_from_dts IS 'Inclusive business validity start.';
COMMENT ON COLUMN search.entity_embedding.valid_to_dts IS 'Exclusive business validity end; infinity means open.';
COMMENT ON COLUMN search.entity_embedding.is_current IS 'Convenience flag agreeing with the open validity end.';
COMMENT ON COLUMN search.entity_embedding.is_deleted IS 'This version records logical deletion; retained for audit.';
COMMENT ON COLUMN search.entity_embedding.deleted_dts IS 'Effective deletion instant; null until deletion.';
COMMENT ON COLUMN search.entity_embedding.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN search.entity_embedding.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW search.v_entity_embedding AS SELECT embedding_id, entity_id, entity_kind, source_module, source_attribute, embedding, embedding_dimensions, embedding_model, embedding_model_version, generated_dts, computation_method, valid_from_dts FROM search.entity_embedding WHERE is_current AND valid_to_dts='infinity'::TIMESTAMPTZ AND NOT is_deleted;
COMMENT ON VIEW search.v_entity_embedding IS 'Consumer contract: Versioned vectors and identifiers; content obtained by Domain join-back.';
CREATE FUNCTION search.at_entity_embedding(at_dts TIMESTAMPTZ) RETURNS SETOF search.entity_embedding LANGUAGE SQL STABLE AS $$ SELECT * FROM search.entity_embedding WHERE valid_from_dts <= at_dts AND at_dts < valid_to_dts AND NOT is_deleted; $$;
CREATE UNIQUE INDEX ON search.entity_embedding (embedding_id) WHERE is_current;
ALTER TABLE search.entity_embedding ADD EXCLUDE USING gist (embedding_id WITH =, tstzrange(valid_from_dts, valid_to_dts, '[)') WITH &&);

