-- Generated by implementation/postgres/render.py; edit model.py.
CREATE TABLE semantic.data_product_registry (
    product_id VARCHAR NOT NULL,
    product_version VARCHAR NOT NULL,
    product_status VARCHAR NOT NULL,
    owner_team VARCHAR NOT NULL,
    trust_authoritative_producer VARCHAR NOT NULL,
    approved_entrypoint VARCHAR NOT NULL,
    approved_access_mode VARCHAR NOT NULL,
    max_evidence_age_days INTEGER NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (product_id)
);
COMMENT ON TABLE semantic.data_product_registry IS 'Product-first discovery anchor; one row per portable product.';
COMMENT ON COLUMN semantic.data_product_registry.product_id IS 'Stable product name supplied to discovery.';
COMMENT ON COLUMN semantic.data_product_registry.product_version IS 'Published contract version.';
COMMENT ON COLUMN semantic.data_product_registry.product_status IS 'Publication lifecycle state.';
COMMENT ON COLUMN semantic.data_product_registry.owner_team IS 'Team responsible for this product.';
COMMENT ON COLUMN semantic.data_product_registry.trust_authoritative_producer IS 'Validator whose latest area evidence defines the trust map.';
COMMENT ON COLUMN semantic.data_product_registry.approved_entrypoint IS 'Fully qualified approved initial business surface.';
COMMENT ON COLUMN semantic.data_product_registry.approved_access_mode IS 'VIEW for this server binding.';
COMMENT ON COLUMN semantic.data_product_registry.max_evidence_age_days IS 'Maximum evidence age before confidence becomes unknown.';
COMMENT ON COLUMN semantic.data_product_registry.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.data_product_registry.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_data_product_registry AS SELECT product_id, product_version, product_status, owner_team, trust_authoritative_producer, approved_entrypoint, approved_access_mode, max_evidence_age_days FROM semantic.data_product_registry;
COMMENT ON VIEW semantic.v_data_product_registry IS 'Consumer contract: Product-first discovery anchor; one row per portable product.';

CREATE TABLE semantic.data_product_map (
    module_name VARCHAR NOT NULL,
    container_name VARCHAR NOT NULL,
    module_purpose VARCHAR NOT NULL,
    deployment_status VARCHAR NOT NULL,
    module_version VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (module_name),
    CHECK (module_name IN ('domain','semantic','search','prediction','observability','memory')),
    CHECK (deployment_status IN ('DEPLOYED','PLANNED','DEPRECATED'))
);
COMMENT ON TABLE semantic.data_product_map IS 'Deployed module discovery map, not design rationale.';
COMMENT ON COLUMN semantic.data_product_map.module_name IS 'Module anchor in the six-module composition.';
COMMENT ON COLUMN semantic.data_product_map.container_name IS 'Exact deployed schema.';
COMMENT ON COLUMN semantic.data_product_map.module_purpose IS 'Capability supplied by the module.';
COMMENT ON COLUMN semantic.data_product_map.deployment_status IS 'DEPLOYED for included modules.';
COMMENT ON COLUMN semantic.data_product_map.module_version IS 'Module contract version.';
COMMENT ON COLUMN semantic.data_product_map.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.data_product_map.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_data_product_map AS SELECT module_name, container_name, module_purpose, deployment_status, module_version FROM semantic.data_product_map;
COMMENT ON VIEW semantic.v_data_product_map IS 'Consumer contract: Deployed module discovery map, not design rationale.';

CREATE TABLE semantic.entity_metadata (
    entity_name VARCHAR NOT NULL,
    entity_description VARCHAR NOT NULL,
    module_name VARCHAR NOT NULL,
    container_name VARCHAR NOT NULL,
    table_name VARCHAR NOT NULL,
    view_name VARCHAR,
    surrogate_key_column VARCHAR NOT NULL,
    natural_key_column VARCHAR NOT NULL,
    temporal_pattern VARCHAR NOT NULL,
    current_flag_column VARCHAR,
    deleted_flag_column VARCHAR,
    standalone_reason VARCHAR,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (entity_name),
    CHECK (module_name IN ('domain','semantic','search','prediction','observability','memory'))
);
COMMENT ON TABLE semantic.entity_metadata IS 'Authored meaning and temporal contract of every governed table.';
COMMENT ON COLUMN semantic.entity_metadata.entity_name IS 'Unique qualified logical entity identity.';
COMMENT ON COLUMN semantic.entity_metadata.entity_description IS 'Purpose and business meaning.';
COMMENT ON COLUMN semantic.entity_metadata.module_name IS 'Owning module anchor.';
COMMENT ON COLUMN semantic.entity_metadata.container_name IS 'Exact deployed schema.';
COMMENT ON COLUMN semantic.entity_metadata.table_name IS 'Exact deployed base table.';
COMMENT ON COLUMN semantic.entity_metadata.view_name IS 'Canonical consumable view; null for private runtime state.';
COMMENT ON COLUMN semantic.entity_metadata.surrogate_key_column IS 'Stable identity column.';
COMMENT ON COLUMN semantic.entity_metadata.natural_key_column IS 'Business-key column or record key.';
COMMENT ON COLUMN semantic.entity_metadata.temporal_pattern IS 'Canonical temporal profile for this persisted table.';
COMMENT ON COLUMN semantic.entity_metadata.current_flag_column IS 'Stored currency flag where versioned.';
COMMENT ON COLUMN semantic.entity_metadata.deleted_flag_column IS 'Stored logical deletion flag where supported.';
COMMENT ON COLUMN semantic.entity_metadata.standalone_reason IS 'Reason an entity needs no relationship traversal.';
COMMENT ON COLUMN semantic.entity_metadata.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.entity_metadata.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_entity_metadata AS SELECT entity_name, entity_description, module_name, container_name, table_name, view_name, surrogate_key_column, natural_key_column, temporal_pattern, current_flag_column, deleted_flag_column, standalone_reason FROM semantic.entity_metadata;
COMMENT ON VIEW semantic.v_entity_metadata IS 'Consumer contract: Authored meaning and temporal contract of every governed table.';

CREATE TABLE semantic.column_metadata (
    column_metadata_id VARCHAR NOT NULL,
    container_name VARCHAR NOT NULL,
    table_name VARCHAR NOT NULL,
    column_name VARCHAR NOT NULL,
    business_description VARCHAR NOT NULL,
    is_pii BOOLEAN NOT NULL,
    is_sensitive BOOLEAN NOT NULL,
    data_classification VARCHAR NOT NULL,
    source VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (column_metadata_id)
);
COMMENT ON TABLE semantic.column_metadata IS 'Authored column meaning kept separately from physical catalogue facts.';
COMMENT ON COLUMN semantic.column_metadata.column_metadata_id IS 'Stable schema.table.column metadata key.';
COMMENT ON COLUMN semantic.column_metadata.container_name IS 'Exact schema.';
COMMENT ON COLUMN semantic.column_metadata.table_name IS 'Exact object name.';
COMMENT ON COLUMN semantic.column_metadata.column_name IS 'Exact field name.';
COMMENT ON COLUMN semantic.column_metadata.business_description IS 'Meaning, units and provenance of the value.';
COMMENT ON COLUMN semantic.column_metadata.is_pii IS 'Whether real deployments could hold personal information.';
COMMENT ON COLUMN semantic.column_metadata.is_sensitive IS 'Whether consumers need handling restrictions.';
COMMENT ON COLUMN semantic.column_metadata.data_classification IS 'Handling classification; synthetic example is PUBLIC.';
COMMENT ON COLUMN semantic.column_metadata.source IS 'Authored source of the semantic description.';
COMMENT ON COLUMN semantic.column_metadata.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.column_metadata.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_column_metadata AS SELECT column_metadata_id, container_name, table_name, column_name, business_description, is_pii, is_sensitive, data_classification, source FROM semantic.column_metadata;
COMMENT ON VIEW semantic.v_column_metadata IS 'Consumer contract: Authored column meaning kept separately from physical catalogue facts.';

CREATE TABLE semantic.table_relationship (
    relationship_id VARCHAR NOT NULL,
    source_entity VARCHAR NOT NULL,
    source_column VARCHAR NOT NULL,
    target_entity VARCHAR NOT NULL,
    target_column VARCHAR NOT NULL,
    cardinality VARCHAR NOT NULL,
    relationship_type VARCHAR NOT NULL,
    is_mandatory BOOLEAN NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (relationship_id)
);
COMMENT ON TABLE semantic.table_relationship IS 'Registered joins including semantic references without physical foreign keys.';
COMMENT ON COLUMN semantic.table_relationship.relationship_id IS 'Stable relationship identity.';
COMMENT ON COLUMN semantic.table_relationship.source_entity IS 'Qualified referencing entity.';
COMMENT ON COLUMN semantic.table_relationship.source_column IS 'Referencing field.';
COMMENT ON COLUMN semantic.table_relationship.target_entity IS 'Qualified referenced entity.';
COMMENT ON COLUMN semantic.table_relationship.target_column IS 'Referenced field.';
COMMENT ON COLUMN semantic.table_relationship.cardinality IS 'Cardinality on current consumable surfaces.';
COMMENT ON COLUMN semantic.table_relationship.relationship_type IS 'FOREIGN_KEY or semantic association.';
COMMENT ON COLUMN semantic.table_relationship.is_mandatory IS 'Whether each source row must resolve.';
COMMENT ON COLUMN semantic.table_relationship.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.table_relationship.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_table_relationship AS SELECT relationship_id, source_entity, source_column, target_entity, target_column, cardinality, relationship_type, is_mandatory FROM semantic.table_relationship;
COMMENT ON VIEW semantic.v_table_relationship IS 'Consumer contract: Registered joins including semantic references without physical foreign keys.';

CREATE TABLE semantic.access_object (
    object_identity VARCHAR NOT NULL,
    access_role VARCHAR NOT NULL,
    represents_entity VARCHAR,
    object_grain VARCHAR NOT NULL,
    is_agent_consumable BOOLEAN NOT NULL,
    resolves_to_object VARCHAR,
    access_note VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (object_identity)
);
COMMENT ON TABLE semantic.access_object IS 'Authoritative access classification established from generated view structure.';
COMMENT ON COLUMN semantic.access_object.object_identity IS 'Exact qualified consumable object.';
COMMENT ON COLUMN semantic.access_object.access_role IS 'BASE, PASSTHROUGH or COMPOSITE.';
COMMENT ON COLUMN semantic.access_object.represents_entity IS 'Entity represented; null for composite objects.';
COMMENT ON COLUMN semantic.access_object.object_grain IS 'One row represents this unit.';
COMMENT ON COLUMN semantic.access_object.is_agent_consumable IS 'Whether this is a public analytical surface.';
COMMENT ON COLUMN semantic.access_object.resolves_to_object IS 'Base object exposed by a passthrough.';
COMMENT ON COLUMN semantic.access_object.access_note IS 'Filtering and safe-use guidance.';
COMMENT ON COLUMN semantic.access_object.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.access_object.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_access_object AS SELECT object_identity, access_role, represents_entity, object_grain, is_agent_consumable, resolves_to_object, access_note FROM semantic.access_object;
COMMENT ON VIEW semantic.v_access_object IS 'Consumer contract: Authoritative access classification established from generated view structure.';

CREATE TABLE semantic.access_composition (
    access_composition_id VARCHAR NOT NULL,
    composite_object VARCHAR NOT NULL,
    member_entity VARCHAR NOT NULL,
    member_role VARCHAR NOT NULL,
    join_path VARCHAR NOT NULL,
    is_grain_contributor BOOLEAN NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (access_composition_id)
);
COMMENT ON TABLE semantic.access_composition IS 'Declared members of joined surfaces; consumers never parse DDL.';
COMMENT ON COLUMN semantic.access_composition.access_composition_id IS 'Composite and member identity.';
COMMENT ON COLUMN semantic.access_composition.composite_object IS 'Exact joined view.';
COMMENT ON COLUMN semantic.access_composition.member_entity IS 'Qualified catalogued member.';
COMMENT ON COLUMN semantic.access_composition.member_role IS 'ANCHOR or joined-member role.';
COMMENT ON COLUMN semantic.access_composition.join_path IS 'Explicit join predicate; empty for anchor.';
COMMENT ON COLUMN semantic.access_composition.is_grain_contributor IS 'Whether member changes row grain.';
COMMENT ON COLUMN semantic.access_composition.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.access_composition.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_access_composition AS SELECT access_composition_id, composite_object, member_entity, member_role, join_path, is_grain_contributor FROM semantic.access_composition;
COMMENT ON VIEW semantic.v_access_composition IS 'Consumer contract: Declared members of joined surfaces; consumers never parse DDL.';

CREATE TABLE semantic.primary_object (
    object_identity VARCHAR NOT NULL,
    module_name VARCHAR NOT NULL,
    object_type VARCHAR NOT NULL,
    object_role VARCHAR NOT NULL,
    usage_guidance VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (object_identity),
    CHECK (module_name IN ('domain','semantic','search','prediction','observability','memory'))
);
COMMENT ON TABLE semantic.primary_object IS 'Module entrypoints with explicit roles and identities.';
COMMENT ON COLUMN semantic.primary_object.object_identity IS 'Verbatim deployed object identity.';
COMMENT ON COLUMN semantic.primary_object.module_name IS 'Owning module.';
COMMENT ON COLUMN semantic.primary_object.object_type IS 'VIEW in this binding.';
COMMENT ON COLUMN semantic.primary_object.object_role IS 'Controlled discovery role.';
COMMENT ON COLUMN semantic.primary_object.usage_guidance IS 'How an agent should use this object.';
COMMENT ON COLUMN semantic.primary_object.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.primary_object.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_primary_object AS SELECT object_identity, module_name, object_type, object_role, usage_guidance FROM semantic.primary_object;
COMMENT ON VIEW semantic.v_primary_object IS 'Consumer contract: Module entrypoints with explicit roles and identities.';

CREATE TABLE semantic.data_product_orientation (
    resource_role VARCHAR NOT NULL,
    product_id VARCHAR NOT NULL,
    object_identity VARCHAR NOT NULL,
    discovery_order INTEGER NOT NULL,
    is_required BOOLEAN NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (resource_role)
);
COMMENT ON TABLE semantic.data_product_orientation IS 'Ordered resources resolved before analytical use.';
COMMENT ON COLUMN semantic.data_product_orientation.resource_role IS 'One resource role per row.';
COMMENT ON COLUMN semantic.data_product_orientation.product_id IS 'Registry product name.';
COMMENT ON COLUMN semantic.data_product_orientation.object_identity IS 'Verbatim database resource name.';
COMMENT ON COLUMN semantic.data_product_orientation.discovery_order IS 'Ascending navigation order; trust precedes analytics.';
COMMENT ON COLUMN semantic.data_product_orientation.is_required IS 'Missing required resources fail conformance.';
COMMENT ON COLUMN semantic.data_product_orientation.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.data_product_orientation.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_data_product_orientation AS SELECT resource_role, product_id, object_identity, discovery_order, is_required FROM semantic.data_product_orientation;
COMMENT ON VIEW semantic.v_data_product_orientation IS 'Consumer contract: Ordered resources resolved before analytical use.';

CREATE TABLE semantic.naming_standard (
    standard_value VARCHAR NOT NULL,
    meaning VARCHAR NOT NULL,
    applies_to VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (standard_value)
);
COMMENT ON TABLE semantic.naming_standard IS 'Declared signals aid authors; consumers use registered identities.';
COMMENT ON COLUMN semantic.naming_standard.standard_value IS 'Naming token or pattern.';
COMMENT ON COLUMN semantic.naming_standard.meaning IS 'Meaning of the convention.';
COMMENT ON COLUMN semantic.naming_standard.applies_to IS 'Object or column scope.';
COMMENT ON COLUMN semantic.naming_standard.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.naming_standard.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_naming_standard AS SELECT standard_value, meaning, applies_to FROM semantic.naming_standard;
COMMENT ON VIEW semantic.v_naming_standard IS 'Consumer contract: Declared signals aid authors; consumers use registered identities.';

CREATE TABLE semantic.metric (
    metric_name VARCHAR NOT NULL,
    metric_description VARCHAR NOT NULL,
    unit VARCHAR NOT NULL,
    aggregation_type VARCHAR NOT NULL,
    grain_description VARCHAR NOT NULL,
    is_additive BOOLEAN NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (metric_name)
);
COMMENT ON TABLE semantic.metric IS 'Business measures with explicit grain and additivity.';
COMMENT ON COLUMN semantic.metric.metric_name IS 'Unique business measure.';
COMMENT ON COLUMN semantic.metric.metric_description IS 'Meaning and exclusions.';
COMMENT ON COLUMN semantic.metric.unit IS 'Measure unit.';
COMMENT ON COLUMN semantic.metric.aggregation_type IS 'Aggregation rule.';
COMMENT ON COLUMN semantic.metric.grain_description IS 'Evaluation grain.';
COMMENT ON COLUMN semantic.metric.is_additive IS 'Whether additive across all dimensions including time.';
COMMENT ON COLUMN semantic.metric.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.metric.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_metric AS SELECT metric_name, metric_description, unit, aggregation_type, grain_description, is_additive FROM semantic.metric;
COMMENT ON VIEW semantic.v_metric IS 'Consumer contract: Business measures with explicit grain and additivity.';

CREATE TABLE semantic.metric_expression (
    expression_id VARCHAR NOT NULL,
    metric_name VARCHAR NOT NULL,
    sql_dialect VARCHAR NOT NULL,
    expression_text VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (expression_id),
    UNIQUE(metric_name, sql_dialect)
);
COMMENT ON TABLE semantic.metric_expression IS 'One expression per metric and SQL dialect.';
COMMENT ON COLUMN semantic.metric_expression.expression_id IS 'Metric-dialect key.';
COMMENT ON COLUMN semantic.metric_expression.metric_name IS 'Registered metric.';
COMMENT ON COLUMN semantic.metric_expression.sql_dialect IS 'Expression dialect.';
COMMENT ON COLUMN semantic.metric_expression.expression_text IS 'Calculation expression.';
COMMENT ON COLUMN semantic.metric_expression.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.metric_expression.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_metric_expression AS SELECT expression_id, metric_name, sql_dialect, expression_text FROM semantic.metric_expression;
COMMENT ON VIEW semantic.v_metric_expression IS 'Consumer contract: One expression per metric and SQL dialect.';

CREATE TABLE semantic.metric_dataset (
    metric_dataset_id VARCHAR NOT NULL,
    metric_name VARCHAR NOT NULL,
    entity_name VARCHAR NOT NULL,
    dataset_role VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (metric_dataset_id),
    CHECK (dataset_role IN ('PRIMARY','JOINED'))
);
COMMENT ON TABLE semantic.metric_dataset IS 'Datasets required by a metric without expression parsing.';
COMMENT ON COLUMN semantic.metric_dataset.metric_dataset_id IS 'Metric-entity key.';
COMMENT ON COLUMN semantic.metric_dataset.metric_name IS 'Registered metric.';
COMMENT ON COLUMN semantic.metric_dataset.entity_name IS 'Registered dataset.';
COMMENT ON COLUMN semantic.metric_dataset.dataset_role IS 'PRIMARY or JOINED.';
COMMENT ON COLUMN semantic.metric_dataset.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.metric_dataset.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_metric_dataset AS SELECT metric_dataset_id, metric_name, entity_name, dataset_role FROM semantic.metric_dataset;
COMMENT ON VIEW semantic.v_metric_dataset IS 'Consumer contract: Datasets required by a metric without expression parsing.';

CREATE TABLE semantic.semantic_synonym (
    synonym_id VARCHAR NOT NULL,
    object_kind VARCHAR NOT NULL,
    object_name VARCHAR NOT NULL,
    synonym_text VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (synonym_id),
    UNIQUE(object_kind, object_name, synonym_text),
    CHECK (object_kind IN ('ENTITY','COLUMN','METRIC'))
);
COMMENT ON TABLE semantic.semantic_synonym IS 'Aliases for resolver matching, distinct from glossary definitions.';
COMMENT ON COLUMN semantic.semantic_synonym.synonym_id IS 'Object-alias key.';
COMMENT ON COLUMN semantic.semantic_synonym.object_kind IS 'ENTITY, COLUMN or METRIC.';
COMMENT ON COLUMN semantic.semantic_synonym.object_name IS 'Registered entity, field or metric identity.';
COMMENT ON COLUMN semantic.semantic_synonym.synonym_text IS 'Alternative consumer term.';
COMMENT ON COLUMN semantic.semantic_synonym.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.semantic_synonym.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_semantic_synonym AS SELECT synonym_id, object_kind, object_name, synonym_text FROM semantic.semantic_synonym;
COMMENT ON VIEW semantic.v_semantic_synonym IS 'Consumer contract: Aliases for resolver matching, distinct from glossary definitions.';

CREATE TABLE semantic.model_metadata (
    model_key VARCHAR NOT NULL,
    model_version VARCHAR NOT NULL,
    model_purpose VARCHAR NOT NULL,
    dimensions INTEGER,
    computation_logic VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (model_key)
);
COMMENT ON TABLE semantic.model_metadata IS 'Versioned model identity and computation provenance.';
COMMENT ON COLUMN semantic.model_metadata.model_key IS 'Model and version identity.';
COMMENT ON COLUMN semantic.model_metadata.model_version IS 'Reproducible model version.';
COMMENT ON COLUMN semantic.model_metadata.model_purpose IS 'Embedding or scoring purpose and limitations.';
COMMENT ON COLUMN semantic.model_metadata.dimensions IS 'Embedding dimension; null for scalar scoring.';
COMMENT ON COLUMN semantic.model_metadata.computation_logic IS 'Reproducible model computation description.';
COMMENT ON COLUMN semantic.model_metadata.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.model_metadata.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_model_metadata AS SELECT model_key, model_version, model_purpose, dimensions, computation_logic FROM semantic.model_metadata;
COMMENT ON VIEW semantic.v_model_metadata IS 'Consumer contract: Versioned model identity and computation provenance.';

CREATE TABLE semantic.feature_definition (
    feature_name VARCHAR NOT NULL,
    feature_version VARCHAR NOT NULL,
    computation_logic VARCHAR NOT NULL,
    source_entity VARCHAR NOT NULL,
    refresh_frequency VARCHAR NOT NULL,
    unit VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (feature_name)
);
COMMENT ON TABLE semantic.feature_definition IS 'Engineering definitions; values belong to Prediction.';
COMMENT ON COLUMN semantic.feature_definition.feature_name IS 'Registered engineered feature.';
COMMENT ON COLUMN semantic.feature_definition.feature_version IS 'Engineering version.';
COMMENT ON COLUMN semantic.feature_definition.computation_logic IS 'Transformation and leakage cutoff.';
COMMENT ON COLUMN semantic.feature_definition.source_entity IS 'Authoritative source dataset.';
COMMENT ON COLUMN semantic.feature_definition.refresh_frequency IS 'Refresh schedule.';
COMMENT ON COLUMN semantic.feature_definition.unit IS 'Normalised unit and bounds.';
COMMENT ON COLUMN semantic.feature_definition.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.feature_definition.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_feature_definition AS SELECT feature_name, feature_version, computation_logic, source_entity, refresh_frequency, unit FROM semantic.feature_definition;
COMMENT ON VIEW semantic.v_feature_definition IS 'Consumer contract: Engineering definitions; values belong to Prediction.';

CREATE TABLE semantic.role_policy (
    role_name VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    enforcement VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (role_name)
);
COMMENT ON TABLE semantic.role_policy IS 'Native PostgreSQL group roles and enforcement boundary.';
COMMENT ON COLUMN semantic.role_policy.role_name IS 'Product logical tier name.';
COMMENT ON COLUMN semantic.role_policy.description IS 'Intended audience only.';
COMMENT ON COLUMN semantic.role_policy.enforcement IS 'Native grants and runtime row security.';
COMMENT ON COLUMN semantic.role_policy.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN semantic.role_policy.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW semantic.v_role_policy AS SELECT role_name, description, enforcement FROM semantic.role_policy;
COMMENT ON VIEW semantic.v_role_policy IS 'Consumer contract: Native PostgreSQL group roles and enforcement boundary.';

