-- Generated by implementation/duckdb/render.py; edit model.py.
CREATE TABLE observability.change_event (
    change_event_id BIGINT NOT NULL,
    table_name VARCHAR NOT NULL,
    change_type VARCHAR NOT NULL,
    change_dts TIMESTAMPTZ NOT NULL,
    changed_by VARCHAR NOT NULL,
    records_affected INTEGER NOT NULL,
    batch_key VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (change_event_id)
);
COMMENT ON TABLE observability.change_event IS 'Append-only operational evidence: change event.';
COMMENT ON COLUMN observability.change_event.change_event_id IS 'Stable surrogate identifying change event; never recycled.';
COMMENT ON COLUMN observability.change_event.table_name IS 'Qualified changed table; no row identifiers.';
COMMENT ON COLUMN observability.change_event.change_type IS 'Mutation kind.';
COMMENT ON COLUMN observability.change_event.change_dts IS 'Change occurred.';
COMMENT ON COLUMN observability.change_event.changed_by IS 'Responsible producer.';
COMMENT ON COLUMN observability.change_event.records_affected IS 'Aggregate count only.';
COMMENT ON COLUMN observability.change_event.batch_key IS 'Producing run identity.';
COMMENT ON COLUMN observability.change_event.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN observability.change_event.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW observability.v_change_event AS SELECT change_event_id, table_name, change_type, change_dts, changed_by, records_affected, batch_key FROM observability.change_event;
COMMENT ON VIEW observability.v_change_event IS 'Consumer contract: Append-only operational evidence: change event.';

CREATE TABLE observability.data_quality_metric (
    quality_metric_id BIGINT NOT NULL,
    table_name VARCHAR NOT NULL,
    metric_name VARCHAR NOT NULL,
    metric_value DECIMAL(10,4) NOT NULL,
    measured_dts TIMESTAMPTZ NOT NULL,
    quality_threshold DECIMAL(5,4) NOT NULL,
    is_threshold_met BOOLEAN NOT NULL,
    sample_size INTEGER NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (quality_metric_id)
);
COMMENT ON TABLE observability.data_quality_metric IS 'Append-only operational evidence: data quality metric.';
COMMENT ON COLUMN observability.data_quality_metric.quality_metric_id IS 'Stable surrogate identifying quality measurement; never recycled.';
COMMENT ON COLUMN observability.data_quality_metric.table_name IS 'Qualified measured table.';
COMMENT ON COLUMN observability.data_quality_metric.metric_name IS 'Data quality dimension.';
COMMENT ON COLUMN observability.data_quality_metric.metric_value IS 'Measured fraction, independently of validation coverage.';
COMMENT ON COLUMN observability.data_quality_metric.measured_dts IS 'Measurement instant.';
COMMENT ON COLUMN observability.data_quality_metric.quality_threshold IS 'Acceptance threshold.';
COMMENT ON COLUMN observability.data_quality_metric.is_threshold_met IS 'Measurement meets declared threshold.';
COMMENT ON COLUMN observability.data_quality_metric.sample_size IS 'Measured population size.';
COMMENT ON COLUMN observability.data_quality_metric.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN observability.data_quality_metric.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW observability.v_data_quality_metric AS SELECT quality_metric_id, table_name, metric_name, metric_value, measured_dts, quality_threshold, is_threshold_met, sample_size FROM observability.data_quality_metric;
COMMENT ON VIEW observability.v_data_quality_metric IS 'Consumer contract: Append-only operational evidence: data quality metric.';

CREATE TABLE observability.lineage_run (
    lineage_run_id BIGINT NOT NULL,
    lineage_id BIGINT NOT NULL,
    run_dts TIMESTAMPTZ NOT NULL,
    run_status VARCHAR NOT NULL,
    records_read INTEGER,
    records_written INTEGER,
    batch_key VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (lineage_run_id),
    CHECK (run_status IN ('SUCCESS','FAILED','PARTIAL','RUNNING'))
);
COMMENT ON TABLE observability.lineage_run IS 'Append-only operational evidence: lineage run.';
COMMENT ON COLUMN observability.lineage_run.lineage_run_id IS 'Stable surrogate identifying flow execution; never recycled.';
COMMENT ON COLUMN observability.lineage_run.lineage_id IS 'Stable surrogate identifying observability.data_lineage; never recycled.';
COMMENT ON COLUMN observability.lineage_run.run_dts IS 'Execution instant.';
COMMENT ON COLUMN observability.lineage_run.run_status IS 'SUCCESS, FAILED, PARTIAL or RUNNING.';
COMMENT ON COLUMN observability.lineage_run.records_read IS 'Input count.';
COMMENT ON COLUMN observability.lineage_run.records_written IS 'Output count.';
COMMENT ON COLUMN observability.lineage_run.batch_key IS 'Execution batch identity.';
COMMENT ON COLUMN observability.lineage_run.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN observability.lineage_run.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW observability.v_lineage_run AS SELECT lineage_run_id, lineage_id, run_dts, run_status, records_read, records_written, batch_key FROM observability.lineage_run;
COMMENT ON VIEW observability.v_lineage_run IS 'Consumer contract: Append-only operational evidence: lineage run.';

CREATE TABLE observability.model_performance (
    performance_id BIGINT NOT NULL,
    model_key VARCHAR NOT NULL,
    model_version VARCHAR NOT NULL,
    metric_name VARCHAR NOT NULL,
    metric_value DECIMAL(10,6),
    evaluation_dts TIMESTAMPTZ NOT NULL,
    sample_size INTEGER,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (performance_id)
);
COMMENT ON TABLE observability.model_performance IS 'Append-only operational evidence: model performance.';
COMMENT ON COLUMN observability.model_performance.performance_id IS 'Stable surrogate identifying model measurement; never recycled.';
COMMENT ON COLUMN observability.model_performance.model_key IS 'Measured model.';
COMMENT ON COLUMN observability.model_performance.model_version IS 'Measured revision.';
COMMENT ON COLUMN observability.model_performance.metric_name IS 'Performance dimension, separate from predictions.';
COMMENT ON COLUMN observability.model_performance.metric_value IS 'Measured metric in named units.';
COMMENT ON COLUMN observability.model_performance.evaluation_dts IS 'Evaluation instant.';
COMMENT ON COLUMN observability.model_performance.sample_size IS 'Evaluation population.';
COMMENT ON COLUMN observability.model_performance.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN observability.model_performance.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW observability.v_model_performance AS SELECT performance_id, model_key, model_version, metric_name, metric_value, evaluation_dts, sample_size FROM observability.model_performance;
COMMENT ON VIEW observability.v_model_performance IS 'Consumer contract: Append-only operational evidence: model performance.';

CREATE TABLE observability.agent_outcome (
    outcome_id BIGINT NOT NULL,
    agent_key VARCHAR NOT NULL,
    session_key VARCHAR NOT NULL,
    action_type VARCHAR NOT NULL,
    action_dts TIMESTAMPTZ NOT NULL,
    tables_accessed VARCHAR NOT NULL,
    outcome_status VARCHAR NOT NULL,
    records_processed INTEGER,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (outcome_id),
    CHECK (outcome_status IN ('SUCCESS','PARTIAL','FAILED'))
);
COMMENT ON TABLE observability.agent_outcome IS 'Append-only operational evidence: agent outcome.';
COMMENT ON COLUMN observability.agent_outcome.outcome_id IS 'Stable surrogate identifying agent outcome; never recycled.';
COMMENT ON COLUMN observability.agent_outcome.agent_key IS 'Acting agent.';
COMMENT ON COLUMN observability.agent_outcome.session_key IS 'Process session identifier.';
COMMENT ON COLUMN observability.agent_outcome.action_type IS 'Process action.';
COMMENT ON COLUMN observability.agent_outcome.action_dts IS 'Action instant.';
COMMENT ON COLUMN observability.agent_outcome.tables_accessed IS 'Table-level references only.';
COMMENT ON COLUMN observability.agent_outcome.outcome_status IS 'Execution result.';
COMMENT ON COLUMN observability.agent_outcome.records_processed IS 'Aggregate count, never result rows.';
COMMENT ON COLUMN observability.agent_outcome.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN observability.agent_outcome.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW observability.v_agent_outcome AS SELECT outcome_id, agent_key, session_key, action_type, action_dts, tables_accessed, outcome_status, records_processed FROM observability.agent_outcome;
COMMENT ON VIEW observability.v_agent_outcome IS 'Consumer contract: Append-only operational evidence: agent outcome.';

CREATE TABLE observability.data_lineage (
    lineage_id BIGINT NOT NULL,
    source_table VARCHAR NOT NULL,
    target_table VARCHAR NOT NULL,
    job_name VARCHAR NOT NULL,
    transformation_logic VARCHAR NOT NULL,
    is_active BOOLEAN NOT NULL,
    registered_dts TIMESTAMPTZ NOT NULL,
    retired_dts TIMESTAMPTZ,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (lineage_id)
);
COMMENT ON TABLE observability.data_lineage IS 'Flow definitions retained independently of executions.';
COMMENT ON COLUMN observability.data_lineage.lineage_id IS 'Stable surrogate identifying flow; never recycled.';
COMMENT ON COLUMN observability.data_lineage.source_table IS 'Qualified source table.';
COMMENT ON COLUMN observability.data_lineage.target_table IS 'Qualified target table.';
COMMENT ON COLUMN observability.data_lineage.job_name IS 'Producing transformation.';
COMMENT ON COLUMN observability.data_lineage.transformation_logic IS 'Transformation definition, without business data.';
COMMENT ON COLUMN observability.data_lineage.is_active IS 'Owner enables or retires a flow; transitions true to false on retirement.';
COMMENT ON COLUMN observability.data_lineage.registered_dts IS 'Flow registered.';
COMMENT ON COLUMN observability.data_lineage.retired_dts IS 'Retirement; null while active.';
COMMENT ON COLUMN observability.data_lineage.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN observability.data_lineage.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW observability.v_data_lineage AS SELECT lineage_id, source_table, target_table, job_name, transformation_logic, is_active, registered_dts, retired_dts FROM observability.data_lineage;
COMMENT ON VIEW observability.v_data_lineage IS 'Consumer contract: Flow definitions retained independently of executions.';

CREATE TABLE observability.retention_policy (
    policy_id VARCHAR NOT NULL,
    retention_days INTEGER,
    rationale VARCHAR NOT NULL,
    owner VARCHAR NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (policy_id)
);
COMMENT ON TABLE observability.retention_policy IS 'Operator-applied retention obligations, not automatic deletion.';
COMMENT ON COLUMN observability.retention_policy.policy_id IS 'Table or facet retention identity.';
COMMENT ON COLUMN observability.retention_policy.retention_days IS 'Null means product lifetime.';
COMMENT ON COLUMN observability.retention_policy.rationale IS 'Why this retention period is used.';
COMMENT ON COLUMN observability.retention_policy.owner IS 'Operator accountable for archival and deletion.';
COMMENT ON COLUMN observability.retention_policy.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN observability.retention_policy.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW observability.v_retention_policy AS SELECT policy_id, retention_days, rationale, owner FROM observability.retention_policy;
COMMENT ON VIEW observability.v_retention_policy IS 'Consumer contract: Operator-applied retention obligations, not automatic deletion.';

CREATE TABLE observability.validation_run (
    product_prefix VARCHAR NOT NULL,
    producer_id VARCHAR NOT NULL,
    run_id VARCHAR NOT NULL,
    producer_version VARCHAR NOT NULL,
    profile_id VARCHAR NOT NULL,
    profile_version VARCHAR NOT NULL,
    source_format VARCHAR NOT NULL,
    payload_schema_version VARCHAR NOT NULL,
    started_dts TIMESTAMPTZ NOT NULL,
    completed_dts TIMESTAMPTZ NOT NULL,
    trust_status VARCHAR NOT NULL CHECK(trust_status IN ('TRUSTED','DEGRADED','UNTRUSTED')),
    agent_use_allowed VARCHAR NOT NULL,
    total_checks INTEGER NOT NULL,
    passed_count INTEGER NOT NULL CHECK (passed_count>=0),
    failed_count INTEGER NOT NULL CHECK (failed_count>=0),
    error_count INTEGER NOT NULL CHECK (error_count>=0),
    critical_failure_count INTEGER NOT NULL CHECK (critical_failure_count>=0),
    error_failure_count INTEGER NOT NULL CHECK (error_failure_count>=0),
    data_product_trust_score INTEGER CHECK(data_product_trust_score BETWEEN 0 AND 100),
    performance_readiness_score INTEGER CHECK(performance_readiness_score BETWEEN 0 AND 100),
    operational_readiness_score INTEGER CHECK(operational_readiness_score BETWEEN 0 AND 100),
    repair_candidate_count INTEGER NOT NULL,
    failed_checks_json JSON,
    repair_candidates_json JSON,
    evidence_expires_dts TIMESTAMPTZ,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (run_id)
);
COMMENT ON TABLE observability.validation_run IS 'Validation wire schema 2.1 run evidence; advisory, never an access gate.';
COMMENT ON COLUMN observability.validation_run.product_prefix IS 'Product evaluated.';
COMMENT ON COLUMN observability.validation_run.producer_id IS 'Validator identity.';
COMMENT ON COLUMN observability.validation_run.run_id IS 'Unique append-only execution identity.';
COMMENT ON COLUMN observability.validation_run.producer_version IS 'Validator version.';
COMMENT ON COLUMN observability.validation_run.profile_id IS 'Executed profile.';
COMMENT ON COLUMN observability.validation_run.profile_version IS 'Profile version.';
COMMENT ON COLUMN observability.validation_run.source_format IS 'Evidence interchange format.';
COMMENT ON COLUMN observability.validation_run.payload_schema_version IS 'Validation wire schema version.';
COMMENT ON COLUMN observability.validation_run.started_dts IS 'Validation started.';
COMMENT ON COLUMN observability.validation_run.completed_dts IS 'Validation completed.';
COMMENT ON COLUMN observability.validation_run.trust_status IS 'Advisory product summary.';
COMMENT ON COLUMN observability.validation_run.agent_use_allowed IS 'Deprecated compatibility field; always go, never authoritative.';
COMMENT ON COLUMN observability.validation_run.total_checks IS 'Executed check count.';
COMMENT ON COLUMN observability.validation_run.passed_count IS 'Checks with PASSED status.';
COMMENT ON COLUMN observability.validation_run.failed_count IS 'Checks with FAILED status.';
COMMENT ON COLUMN observability.validation_run.error_count IS 'Checks that could not execute.';
COMMENT ON COLUMN observability.validation_run.critical_failure_count IS 'Failed or errored CRITICAL checks.';
COMMENT ON COLUMN observability.validation_run.error_failure_count IS 'Failed or errored ERROR-severity checks.';
COMMENT ON COLUMN observability.validation_run.data_product_trust_score IS 'Optional readiness score; null means unassessed.';
COMMENT ON COLUMN observability.validation_run.performance_readiness_score IS 'Optional readiness score; null means unassessed.';
COMMENT ON COLUMN observability.validation_run.operational_readiness_score IS 'Optional readiness score; null means unassessed.';
COMMENT ON COLUMN observability.validation_run.repair_candidate_count IS 'True repair proposal count.';
COMMENT ON COLUMN observability.validation_run.failed_checks_json IS 'Optional capped failure detail; counts remain authoritative.';
COMMENT ON COLUMN observability.validation_run.repair_candidates_json IS 'Optional capped proposals, never executable authority.';
COMMENT ON COLUMN observability.validation_run.evidence_expires_dts IS 'Evidence expiry.';
COMMENT ON COLUMN observability.validation_run.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN observability.validation_run.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW observability.v_validation_run AS SELECT product_prefix, producer_id, run_id, producer_version, profile_id, profile_version, source_format, payload_schema_version, started_dts, completed_dts, trust_status, agent_use_allowed, total_checks, passed_count, failed_count, error_count, critical_failure_count, error_failure_count, data_product_trust_score, performance_readiness_score, operational_readiness_score, repair_candidate_count, failed_checks_json, repair_candidates_json, evidence_expires_dts FROM observability.validation_run;
COMMENT ON VIEW observability.v_validation_run IS 'Consumer contract: Validation wire schema 2.1 run evidence; advisory, never an access gate.';

CREATE TABLE observability.validation_area (
    product_prefix VARCHAR NOT NULL,
    producer_id VARCHAR NOT NULL,
    run_id VARCHAR NOT NULL,
    area_id VARCHAR NOT NULL,
    payload_schema_version VARCHAR NOT NULL,
    scope_kind VARCHAR NOT NULL,
    scope_id VARCHAR NOT NULL,
    checks_expected INTEGER NOT NULL,
    checks_ran INTEGER NOT NULL,
    passed_count INTEGER NOT NULL CHECK (passed_count>=0),
    failed_count INTEGER NOT NULL CHECK (failed_count>=0),
    error_count INTEGER NOT NULL CHECK (error_count>=0),
    critical_failure_count INTEGER NOT NULL CHECK (critical_failure_count>=0),
    error_failure_count INTEGER NOT NULL CHECK (error_failure_count>=0),
    area_status VARCHAR NOT NULL,
    confidence VARCHAR NOT NULL,
    open_gaps VARCHAR,
    recommended_action VARCHAR,
    completed_dts TIMESTAMPTZ NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (area_id),
    CHECK (scope_kind IN ('PRODUCT','MODULE','ENTITY','PATTERN','CAPABILITY')),
    CHECK (area_status IN ('pass','fail','partial','not-validated','no-evidence')),
    CHECK (confidence IN ('strong','partial','weak','unknown'))
);
COMMENT ON TABLE observability.validation_area IS 'Per-area check coverage and confidence for each validation run.';
COMMENT ON COLUMN observability.validation_area.product_prefix IS 'Product evaluated.';
COMMENT ON COLUMN observability.validation_area.producer_id IS 'Validator identity.';
COMMENT ON COLUMN observability.validation_area.run_id IS 'Unique append-only execution identity.';
COMMENT ON COLUMN observability.validation_area.area_id IS 'Run-scope composite identity.';
COMMENT ON COLUMN observability.validation_area.payload_schema_version IS 'Validation wire schema version.';
COMMENT ON COLUMN observability.validation_area.scope_kind IS 'PRODUCT, MODULE, ENTITY, PATTERN or CAPABILITY.';
COMMENT ON COLUMN observability.validation_area.scope_id IS 'Resolvable area identity.';
COMMENT ON COLUMN observability.validation_area.checks_expected IS 'Checks defined by the profile.';
COMMENT ON COLUMN observability.validation_area.checks_ran IS 'Checks executed.';
COMMENT ON COLUMN observability.validation_area.passed_count IS 'Checks with PASSED status.';
COMMENT ON COLUMN observability.validation_area.failed_count IS 'Checks with FAILED status.';
COMMENT ON COLUMN observability.validation_area.error_count IS 'Checks that could not execute.';
COMMENT ON COLUMN observability.validation_area.critical_failure_count IS 'Failed or errored CRITICAL checks.';
COMMENT ON COLUMN observability.validation_area.error_failure_count IS 'Failed or errored ERROR-severity checks.';
COMMENT ON COLUMN observability.validation_area.area_status IS 'pass, fail, partial, not-validated or no-evidence.';
COMMENT ON COLUMN observability.validation_area.confidence IS 'strong, partial, weak or unknown.';
COMMENT ON COLUMN observability.validation_area.open_gaps IS 'Coverage limits, required below strong.';
COMMENT ON COLUMN observability.validation_area.recommended_action IS 'How to raise confidence.';
COMMENT ON COLUMN observability.validation_area.completed_dts IS 'Parent run completion instant.';
COMMENT ON COLUMN observability.validation_area.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN observability.validation_area.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW observability.v_validation_area AS SELECT product_prefix, producer_id, run_id, area_id, payload_schema_version, scope_kind, scope_id, checks_expected, checks_ran, passed_count, failed_count, error_count, critical_failure_count, error_failure_count, area_status, confidence, open_gaps, recommended_action, completed_dts FROM observability.validation_area;
COMMENT ON VIEW observability.v_validation_area IS 'Consumer contract: Per-area check coverage and confidence for each validation run.';

CREATE TABLE observability.validation_check (
    check_result_id VARCHAR NOT NULL,
    run_id VARCHAR NOT NULL,
    test_id VARCHAR NOT NULL,
    scope_kind VARCHAR NOT NULL,
    scope_id VARCHAR NOT NULL,
    category VARCHAR NOT NULL,
    severity VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    row_count INTEGER NOT NULL,
    error_message VARCHAR,
    checked_dts TIMESTAMPTZ NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL,
    updated_dts TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (check_result_id),
    CHECK (scope_kind IN ('PRODUCT','MODULE','ENTITY','PATTERN','CAPABILITY')),
    CHECK (severity IN ('INFO','WARNING','ERROR','CRITICAL')),
    CHECK (status IN ('PASSED','FAILED','ERROR'))
);
COMMENT ON TABLE observability.validation_check IS 'Individual executed check identity and error evidence.';
COMMENT ON COLUMN observability.validation_check.check_result_id IS 'Run and test identity.';
COMMENT ON COLUMN observability.validation_check.run_id IS 'Parent validation run.';
COMMENT ON COLUMN observability.validation_check.test_id IS 'Stable product-family check identifier.';
COMMENT ON COLUMN observability.validation_check.scope_kind IS 'Area kind.';
COMMENT ON COLUMN observability.validation_check.scope_id IS 'Area identity.';
COMMENT ON COLUMN observability.validation_check.category IS 'Check family.';
COMMENT ON COLUMN observability.validation_check.severity IS 'Failure impact.';
COMMENT ON COLUMN observability.validation_check.status IS 'PASSED, FAILED or ERROR.';
COMMENT ON COLUMN observability.validation_check.row_count IS 'True violating row count.';
COMMENT ON COLUMN observability.validation_check.error_message IS 'Execution error only.';
COMMENT ON COLUMN observability.validation_check.checked_dts IS 'Check execution time.';
COMMENT ON COLUMN observability.validation_check.created_dts IS 'Instant this physical row was created.';
COMMENT ON COLUMN observability.validation_check.updated_dts IS 'Instant this physical row was last changed.';
CREATE VIEW observability.v_validation_check AS SELECT check_result_id, run_id, test_id, scope_kind, scope_id, category, severity, status, row_count, error_message, checked_dts FROM observability.validation_check;
COMMENT ON VIEW observability.v_validation_check IS 'Consumer contract: Individual executed check identity and error evidence.';

